/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTagDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTagDataAttributes{}

// CreateTagDataAttributes struct for CreateTagDataAttributes
type CreateTagDataAttributes struct {
	// tag name
	Name string `json:"name"`
	// tag status
	Status string `json:"status"`
	// tag type
	Type string `json:"type"`
	// tag color
	Color string `json:"color"`
	// tag icon
	Icon string `json:"icon"`
}

type _CreateTagDataAttributes CreateTagDataAttributes

// NewCreateTagDataAttributes instantiates a new CreateTagDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTagDataAttributes(name string, status string, type_ string, color string, icon string) *CreateTagDataAttributes {
	this := CreateTagDataAttributes{}
	this.Name = name
	this.Status = status
	this.Type = type_
	this.Color = color
	this.Icon = icon
	return &this
}

// NewCreateTagDataAttributesWithDefaults instantiates a new CreateTagDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTagDataAttributesWithDefaults() *CreateTagDataAttributes {
	this := CreateTagDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateTagDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTagDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTagDataAttributes) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *CreateTagDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateTagDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateTagDataAttributes) SetStatus(v string) {
	o.Status = v
}

// GetType returns the Type field value
func (o *CreateTagDataAttributes) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateTagDataAttributes) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateTagDataAttributes) SetType(v string) {
	o.Type = v
}

// GetColor returns the Color field value
func (o *CreateTagDataAttributes) GetColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Color
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
func (o *CreateTagDataAttributes) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color, true
}

// SetColor sets field value
func (o *CreateTagDataAttributes) SetColor(v string) {
	o.Color = v
}

// GetIcon returns the Icon field value
func (o *CreateTagDataAttributes) GetIcon() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *CreateTagDataAttributes) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *CreateTagDataAttributes) SetIcon(v string) {
	o.Icon = v
}

func (o CreateTagDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTagDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type
	toSerialize["color"] = o.Color
	toSerialize["icon"] = o.Icon
	return toSerialize, nil
}

func (o *CreateTagDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"status",
		"type",
		"color",
		"icon",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTagDataAttributes := _CreateTagDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTagDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateTagDataAttributes(varCreateTagDataAttributes)

	return err
}

type NullableCreateTagDataAttributes struct {
	value *CreateTagDataAttributes
	isSet bool
}

func (v NullableCreateTagDataAttributes) Get() *CreateTagDataAttributes {
	return v.value
}

func (v *NullableCreateTagDataAttributes) Set(val *CreateTagDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTagDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTagDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTagDataAttributes(val *CreateTagDataAttributes) *NullableCreateTagDataAttributes {
	return &NullableCreateTagDataAttributes{value: val, isSet: true}
}

func (v NullableCreateTagDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTagDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


