/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorsCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorsCollectionData{}

// AuthorsCollectionData struct for AuthorsCollectionData
type AuthorsCollectionData struct {
	Type string `json:"type"`
	Attributes AuthorsCollectionDataAttributes `json:"attributes"`
}

type _AuthorsCollectionData AuthorsCollectionData

// NewAuthorsCollectionData instantiates a new AuthorsCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorsCollectionData(type_ string, attributes AuthorsCollectionDataAttributes) *AuthorsCollectionData {
	this := AuthorsCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAuthorsCollectionDataWithDefaults instantiates a new AuthorsCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorsCollectionDataWithDefaults() *AuthorsCollectionData {
	this := AuthorsCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *AuthorsCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AuthorsCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AuthorsCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AuthorsCollectionData) GetAttributes() AuthorsCollectionDataAttributes {
	if o == nil {
		var ret AuthorsCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AuthorsCollectionData) GetAttributesOk() (*AuthorsCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AuthorsCollectionData) SetAttributes(v AuthorsCollectionDataAttributes) {
	o.Attributes = v
}

func (o AuthorsCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorsCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *AuthorsCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorsCollectionData := _AuthorsCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorsCollectionData)

	if err != nil {
		return err
	}

	*o = AuthorsCollectionData(varAuthorsCollectionData)

	return err
}

type NullableAuthorsCollectionData struct {
	value *AuthorsCollectionData
	isSet bool
}

func (v NullableAuthorsCollectionData) Get() *AuthorsCollectionData {
	return v.value
}

func (v *NullableAuthorsCollectionData) Set(val *AuthorsCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorsCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorsCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorsCollectionData(val *AuthorsCollectionData) *NullableAuthorsCollectionData {
	return &NullableAuthorsCollectionData{value: val, isSet: true}
}

func (v NullableAuthorsCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorsCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


