/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorUpdateData{}

// AuthorUpdateData struct for AuthorUpdateData
type AuthorUpdateData struct {
	Type string `json:"type"`
	Attributes AuthorUpdateDataAttributes `json:"attributes"`
}

type _AuthorUpdateData AuthorUpdateData

// NewAuthorUpdateData instantiates a new AuthorUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorUpdateData(type_ string, attributes AuthorUpdateDataAttributes) *AuthorUpdateData {
	this := AuthorUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAuthorUpdateDataWithDefaults instantiates a new AuthorUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorUpdateDataWithDefaults() *AuthorUpdateData {
	this := AuthorUpdateData{}
	return &this
}

// GetType returns the Type field value
func (o *AuthorUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AuthorUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AuthorUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AuthorUpdateData) GetAttributes() AuthorUpdateDataAttributes {
	if o == nil {
		var ret AuthorUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AuthorUpdateData) GetAttributesOk() (*AuthorUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AuthorUpdateData) SetAttributes(v AuthorUpdateDataAttributes) {
	o.Attributes = v
}

func (o AuthorUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *AuthorUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorUpdateData := _AuthorUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorUpdateData)

	if err != nil {
		return err
	}

	*o = AuthorUpdateData(varAuthorUpdateData)

	return err
}

type NullableAuthorUpdateData struct {
	value *AuthorUpdateData
	isSet bool
}

func (v NullableAuthorUpdateData) Get() *AuthorUpdateData {
	return v.value
}

func (v *NullableAuthorUpdateData) Set(val *AuthorUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorUpdateData(val *AuthorUpdateData) *NullableAuthorUpdateData {
	return &NullableAuthorUpdateData{value: val, isSet: true}
}

func (v NullableAuthorUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


