/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAuthorDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAuthorDataAttributes{}

// CreateAuthorDataAttributes struct for CreateAuthorDataAttributes
type CreateAuthorDataAttributes struct {
	Name string `json:"name"`
	Desc *string `json:"desc,omitempty"`
	Avatar *string `json:"avatar,omitempty"`
	Email *string `json:"email,omitempty"`
	Telegram *string `json:"telegram,omitempty"`
	Twitter *string `json:"twitter,omitempty"`
}

type _CreateAuthorDataAttributes CreateAuthorDataAttributes

// NewCreateAuthorDataAttributes instantiates a new CreateAuthorDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAuthorDataAttributes(name string) *CreateAuthorDataAttributes {
	this := CreateAuthorDataAttributes{}
	this.Name = name
	return &this
}

// NewCreateAuthorDataAttributesWithDefaults instantiates a new CreateAuthorDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAuthorDataAttributesWithDefaults() *CreateAuthorDataAttributes {
	this := CreateAuthorDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAuthorDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAuthorDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAuthorDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *CreateAuthorDataAttributes) GetDesc() string {
	if o == nil || IsNil(o.Desc) {
		var ret string
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAuthorDataAttributes) GetDescOk() (*string, bool) {
	if o == nil || IsNil(o.Desc) {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *CreateAuthorDataAttributes) HasDesc() bool {
	if o != nil && !IsNil(o.Desc) {
		return true
	}

	return false
}

// SetDesc gets a reference to the given string and assigns it to the Desc field.
func (o *CreateAuthorDataAttributes) SetDesc(v string) {
	o.Desc = &v
}

// GetAvatar returns the Avatar field value if set, zero value otherwise.
func (o *CreateAuthorDataAttributes) GetAvatar() string {
	if o == nil || IsNil(o.Avatar) {
		var ret string
		return ret
	}
	return *o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAuthorDataAttributes) GetAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.Avatar) {
		return nil, false
	}
	return o.Avatar, true
}

// HasAvatar returns a boolean if a field has been set.
func (o *CreateAuthorDataAttributes) HasAvatar() bool {
	if o != nil && !IsNil(o.Avatar) {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given string and assigns it to the Avatar field.
func (o *CreateAuthorDataAttributes) SetAvatar(v string) {
	o.Avatar = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateAuthorDataAttributes) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAuthorDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateAuthorDataAttributes) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateAuthorDataAttributes) SetEmail(v string) {
	o.Email = &v
}

// GetTelegram returns the Telegram field value if set, zero value otherwise.
func (o *CreateAuthorDataAttributes) GetTelegram() string {
	if o == nil || IsNil(o.Telegram) {
		var ret string
		return ret
	}
	return *o.Telegram
}

// GetTelegramOk returns a tuple with the Telegram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAuthorDataAttributes) GetTelegramOk() (*string, bool) {
	if o == nil || IsNil(o.Telegram) {
		return nil, false
	}
	return o.Telegram, true
}

// HasTelegram returns a boolean if a field has been set.
func (o *CreateAuthorDataAttributes) HasTelegram() bool {
	if o != nil && !IsNil(o.Telegram) {
		return true
	}

	return false
}

// SetTelegram gets a reference to the given string and assigns it to the Telegram field.
func (o *CreateAuthorDataAttributes) SetTelegram(v string) {
	o.Telegram = &v
}

// GetTwitter returns the Twitter field value if set, zero value otherwise.
func (o *CreateAuthorDataAttributes) GetTwitter() string {
	if o == nil || IsNil(o.Twitter) {
		var ret string
		return ret
	}
	return *o.Twitter
}

// GetTwitterOk returns a tuple with the Twitter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAuthorDataAttributes) GetTwitterOk() (*string, bool) {
	if o == nil || IsNil(o.Twitter) {
		return nil, false
	}
	return o.Twitter, true
}

// HasTwitter returns a boolean if a field has been set.
func (o *CreateAuthorDataAttributes) HasTwitter() bool {
	if o != nil && !IsNil(o.Twitter) {
		return true
	}

	return false
}

// SetTwitter gets a reference to the given string and assigns it to the Twitter field.
func (o *CreateAuthorDataAttributes) SetTwitter(v string) {
	o.Twitter = &v
}

func (o CreateAuthorDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAuthorDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Desc) {
		toSerialize["desc"] = o.Desc
	}
	if !IsNil(o.Avatar) {
		toSerialize["avatar"] = o.Avatar
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Telegram) {
		toSerialize["telegram"] = o.Telegram
	}
	if !IsNil(o.Twitter) {
		toSerialize["twitter"] = o.Twitter
	}
	return toSerialize, nil
}

func (o *CreateAuthorDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAuthorDataAttributes := _CreateAuthorDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAuthorDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateAuthorDataAttributes(varCreateAuthorDataAttributes)

	return err
}

type NullableCreateAuthorDataAttributes struct {
	value *CreateAuthorDataAttributes
	isSet bool
}

func (v NullableCreateAuthorDataAttributes) Get() *CreateAuthorDataAttributes {
	return v.value
}

func (v *NullableCreateAuthorDataAttributes) Set(val *CreateAuthorDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAuthorDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAuthorDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAuthorDataAttributes(val *CreateAuthorDataAttributes) *NullableCreateAuthorDataAttributes {
	return &NullableCreateAuthorDataAttributes{value: val, isSet: true}
}

func (v NullableCreateAuthorDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAuthorDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


