/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleShortCollectionDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleShortCollectionDataAttributes{}

// ArticleShortCollectionDataAttributes struct for ArticleShortCollectionDataAttributes
type ArticleShortCollectionDataAttributes struct {
	Data []ArticleShortData `json:"data"`
}

type _ArticleShortCollectionDataAttributes ArticleShortCollectionDataAttributes

// NewArticleShortCollectionDataAttributes instantiates a new ArticleShortCollectionDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleShortCollectionDataAttributes(data []ArticleShortData) *ArticleShortCollectionDataAttributes {
	this := ArticleShortCollectionDataAttributes{}
	this.Data = data
	return &this
}

// NewArticleShortCollectionDataAttributesWithDefaults instantiates a new ArticleShortCollectionDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleShortCollectionDataAttributesWithDefaults() *ArticleShortCollectionDataAttributes {
	this := ArticleShortCollectionDataAttributes{}
	return &this
}

// GetData returns the Data field value
func (o *ArticleShortCollectionDataAttributes) GetData() []ArticleShortData {
	if o == nil {
		var ret []ArticleShortData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ArticleShortCollectionDataAttributes) GetDataOk() ([]ArticleShortData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ArticleShortCollectionDataAttributes) SetData(v []ArticleShortData) {
	o.Data = v
}

func (o ArticleShortCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleShortCollectionDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ArticleShortCollectionDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleShortCollectionDataAttributes := _ArticleShortCollectionDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleShortCollectionDataAttributes)

	if err != nil {
		return err
	}

	*o = ArticleShortCollectionDataAttributes(varArticleShortCollectionDataAttributes)

	return err
}

type NullableArticleShortCollectionDataAttributes struct {
	value *ArticleShortCollectionDataAttributes
	isSet bool
}

func (v NullableArticleShortCollectionDataAttributes) Get() *ArticleShortCollectionDataAttributes {
	return v.value
}

func (v *NullableArticleShortCollectionDataAttributes) Set(val *ArticleShortCollectionDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleShortCollectionDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleShortCollectionDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleShortCollectionDataAttributes(val *ArticleShortCollectionDataAttributes) *NullableArticleShortCollectionDataAttributes {
	return &NullableArticleShortCollectionDataAttributes{value: val, isSet: true}
}

func (v NullableArticleShortCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleShortCollectionDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


