/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateContentSectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateContentSectionResponse{}

// UpdateContentSectionResponse struct for UpdateContentSectionResponse
type UpdateContentSectionResponse struct {
	// The status of the content update operation.
	Status string `json:"status"`
	// A message providing additional information about the operation.
	Message string `json:"message"`
	Type string `json:"type"`
	Section Section `json:"section"`
}

type _UpdateContentSectionResponse UpdateContentSectionResponse

// NewUpdateContentSectionResponse instantiates a new UpdateContentSectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateContentSectionResponse(status string, message string, type_ string, section Section) *UpdateContentSectionResponse {
	this := UpdateContentSectionResponse{}
	this.Status = status
	this.Message = message
	this.Type = type_
	this.Section = section
	return &this
}

// NewUpdateContentSectionResponseWithDefaults instantiates a new UpdateContentSectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateContentSectionResponseWithDefaults() *UpdateContentSectionResponse {
	this := UpdateContentSectionResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateContentSectionResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateContentSectionResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateContentSectionResponse) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *UpdateContentSectionResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UpdateContentSectionResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UpdateContentSectionResponse) SetMessage(v string) {
	o.Message = v
}

// GetType returns the Type field value
func (o *UpdateContentSectionResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateContentSectionResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateContentSectionResponse) SetType(v string) {
	o.Type = v
}

// GetSection returns the Section field value
func (o *UpdateContentSectionResponse) GetSection() Section {
	if o == nil {
		var ret Section
		return ret
	}

	return o.Section
}

// GetSectionOk returns a tuple with the Section field value
// and a boolean to check if the value has been set.
func (o *UpdateContentSectionResponse) GetSectionOk() (*Section, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Section, true
}

// SetSection sets field value
func (o *UpdateContentSectionResponse) SetSection(v Section) {
	o.Section = v
}

func (o UpdateContentSectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateContentSectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["type"] = o.Type
	toSerialize["section"] = o.Section
	return toSerialize, nil
}

func (o *UpdateContentSectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"message",
		"type",
		"section",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateContentSectionResponse := _UpdateContentSectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateContentSectionResponse)

	if err != nil {
		return err
	}

	*o = UpdateContentSectionResponse(varUpdateContentSectionResponse)

	return err
}

type NullableUpdateContentSectionResponse struct {
	value *UpdateContentSectionResponse
	isSet bool
}

func (v NullableUpdateContentSectionResponse) Get() *UpdateContentSectionResponse {
	return v.value
}

func (v *NullableUpdateContentSectionResponse) Set(val *UpdateContentSectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateContentSectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateContentSectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateContentSectionResponse(val *UpdateContentSectionResponse) *NullableUpdateContentSectionResponse {
	return &NullableUpdateContentSectionResponse{value: val, isSet: true}
}

func (v NullableUpdateContentSectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateContentSectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


