/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagCollection{}

// TagCollection struct for TagCollection
type TagCollection struct {
	Data TagCollectionData `json:"data"`
}

type _TagCollection TagCollection

// NewTagCollection instantiates a new TagCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagCollection(data TagCollectionData) *TagCollection {
	this := TagCollection{}
	this.Data = data
	return &this
}

// NewTagCollectionWithDefaults instantiates a new TagCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagCollectionWithDefaults() *TagCollection {
	this := TagCollection{}
	return &this
}

// GetData returns the Data field value
func (o *TagCollection) GetData() TagCollectionData {
	if o == nil {
		var ret TagCollectionData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TagCollection) GetDataOk() (*TagCollectionData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *TagCollection) SetData(v TagCollectionData) {
	o.Data = v
}

func (o TagCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *TagCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagCollection := _TagCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagCollection)

	if err != nil {
		return err
	}

	*o = TagCollection(varTagCollection)

	return err
}

type NullableTagCollection struct {
	value *TagCollection
	isSet bool
}

func (v NullableTagCollection) Get() *TagCollection {
	return v.value
}

func (v *NullableTagCollection) Set(val *TagCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableTagCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableTagCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagCollection(val *TagCollection) *NullableTagCollection {
	return &NullableTagCollection{value: val, isSet: true}
}

func (v NullableTagCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


