/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateArticleDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateArticleDataAttributes{}

// CreateArticleDataAttributes struct for CreateArticleDataAttributes
type CreateArticleDataAttributes struct {
	// Article title
	Title string `json:"title"`
}

type _CreateArticleDataAttributes CreateArticleDataAttributes

// NewCreateArticleDataAttributes instantiates a new CreateArticleDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateArticleDataAttributes(title string) *CreateArticleDataAttributes {
	this := CreateArticleDataAttributes{}
	this.Title = title
	return &this
}

// NewCreateArticleDataAttributesWithDefaults instantiates a new CreateArticleDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateArticleDataAttributesWithDefaults() *CreateArticleDataAttributes {
	this := CreateArticleDataAttributes{}
	return &this
}

// GetTitle returns the Title field value
func (o *CreateArticleDataAttributes) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CreateArticleDataAttributes) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CreateArticleDataAttributes) SetTitle(v string) {
	o.Title = v
}

func (o CreateArticleDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateArticleDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

func (o *CreateArticleDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateArticleDataAttributes := _CreateArticleDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateArticleDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateArticleDataAttributes(varCreateArticleDataAttributes)

	return err
}

type NullableCreateArticleDataAttributes struct {
	value *CreateArticleDataAttributes
	isSet bool
}

func (v NullableCreateArticleDataAttributes) Get() *CreateArticleDataAttributes {
	return v.value
}

func (v *NullableCreateArticleDataAttributes) Set(val *CreateArticleDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateArticleDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateArticleDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateArticleDataAttributes(val *CreateArticleDataAttributes) *NullableCreateArticleDataAttributes {
	return &NullableCreateArticleDataAttributes{value: val, isSet: true}
}

func (v NullableCreateArticleDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateArticleDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


