/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateArticle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateArticle{}

// CreateArticle struct for CreateArticle
type CreateArticle struct {
	Data CreateArticleData `json:"data"`
}

type _CreateArticle CreateArticle

// NewCreateArticle instantiates a new CreateArticle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateArticle(data CreateArticleData) *CreateArticle {
	this := CreateArticle{}
	this.Data = data
	return &this
}

// NewCreateArticleWithDefaults instantiates a new CreateArticle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateArticleWithDefaults() *CreateArticle {
	this := CreateArticle{}
	return &this
}

// GetData returns the Data field value
func (o *CreateArticle) GetData() CreateArticleData {
	if o == nil {
		var ret CreateArticleData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateArticle) GetDataOk() (*CreateArticleData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateArticle) SetData(v CreateArticleData) {
	o.Data = v
}

func (o CreateArticle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateArticle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateArticle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateArticle := _CreateArticle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateArticle)

	if err != nil {
		return err
	}

	*o = CreateArticle(varCreateArticle)

	return err
}

type NullableCreateArticle struct {
	value *CreateArticle
	isSet bool
}

func (v NullableCreateArticle) Get() *CreateArticle {
	return v.value
}

func (v *NullableCreateArticle) Set(val *CreateArticle) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateArticle) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateArticle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateArticle(val *CreateArticle) *NullableCreateArticle {
	return &NullableCreateArticle{value: val, isSet: true}
}

func (v NullableCreateArticle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateArticle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


