/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HashtagCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HashtagCreate{}

// HashtagCreate struct for HashtagCreate
type HashtagCreate struct {
	Data HashtagCreateData `json:"data"`
}

type _HashtagCreate HashtagCreate

// NewHashtagCreate instantiates a new HashtagCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHashtagCreate(data HashtagCreateData) *HashtagCreate {
	this := HashtagCreate{}
	this.Data = data
	return &this
}

// NewHashtagCreateWithDefaults instantiates a new HashtagCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHashtagCreateWithDefaults() *HashtagCreate {
	this := HashtagCreate{}
	return &this
}

// GetData returns the Data field value
func (o *HashtagCreate) GetData() HashtagCreateData {
	if o == nil {
		var ret HashtagCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *HashtagCreate) GetDataOk() (*HashtagCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *HashtagCreate) SetData(v HashtagCreateData) {
	o.Data = v
}

func (o HashtagCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HashtagCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *HashtagCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHashtagCreate := _HashtagCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHashtagCreate)

	if err != nil {
		return err
	}

	*o = HashtagCreate(varHashtagCreate)

	return err
}

type NullableHashtagCreate struct {
	value *HashtagCreate
	isSet bool
}

func (v NullableHashtagCreate) Get() *HashtagCreate {
	return v.value
}

func (v *NullableHashtagCreate) Set(val *HashtagCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableHashtagCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableHashtagCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHashtagCreate(val *HashtagCreate) *NullableHashtagCreate {
	return &NullableHashtagCreate{value: val, isSet: true}
}

func (v NullableHashtagCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHashtagCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


