/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorCreateData{}

// AuthorCreateData struct for AuthorCreateData
type AuthorCreateData struct {
	Type string `json:"type"`
	Attributes AuthorCreateDataAttributes `json:"attributes"`
}

type _AuthorCreateData AuthorCreateData

// NewAuthorCreateData instantiates a new AuthorCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorCreateData(type_ string, attributes AuthorCreateDataAttributes) *AuthorCreateData {
	this := AuthorCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAuthorCreateDataWithDefaults instantiates a new AuthorCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorCreateDataWithDefaults() *AuthorCreateData {
	this := AuthorCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *AuthorCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AuthorCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AuthorCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AuthorCreateData) GetAttributes() AuthorCreateDataAttributes {
	if o == nil {
		var ret AuthorCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AuthorCreateData) GetAttributesOk() (*AuthorCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AuthorCreateData) SetAttributes(v AuthorCreateDataAttributes) {
	o.Attributes = v
}

func (o AuthorCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *AuthorCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorCreateData := _AuthorCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorCreateData)

	if err != nil {
		return err
	}

	*o = AuthorCreateData(varAuthorCreateData)

	return err
}

type NullableAuthorCreateData struct {
	value *AuthorCreateData
	isSet bool
}

func (v NullableAuthorCreateData) Get() *AuthorCreateData {
	return v.value
}

func (v *NullableAuthorCreateData) Set(val *AuthorCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorCreateData(val *AuthorCreateData) *NullableAuthorCreateData {
	return &NullableAuthorCreateData{value: val, isSet: true}
}

func (v NullableAuthorCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


