/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagCollectionData{}

// TagCollectionData struct for TagCollectionData
type TagCollectionData struct {
	Type string `json:"type"`
	Attributes TagCollectionDataAttributes `json:"attributes"`
}

type _TagCollectionData TagCollectionData

// NewTagCollectionData instantiates a new TagCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagCollectionData(type_ string, attributes TagCollectionDataAttributes) *TagCollectionData {
	this := TagCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewTagCollectionDataWithDefaults instantiates a new TagCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagCollectionDataWithDefaults() *TagCollectionData {
	this := TagCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *TagCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TagCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TagCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *TagCollectionData) GetAttributes() TagCollectionDataAttributes {
	if o == nil {
		var ret TagCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *TagCollectionData) GetAttributesOk() (*TagCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *TagCollectionData) SetAttributes(v TagCollectionDataAttributes) {
	o.Attributes = v
}

func (o TagCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *TagCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagCollectionData := _TagCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagCollectionData)

	if err != nil {
		return err
	}

	*o = TagCollectionData(varTagCollectionData)

	return err
}

type NullableTagCollectionData struct {
	value *TagCollectionData
	isSet bool
}

func (v NullableTagCollectionData) Get() *TagCollectionData {
	return v.value
}

func (v *NullableTagCollectionData) Set(val *TagCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableTagCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableTagCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagCollectionData(val *TagCollectionData) *NullableTagCollectionData {
	return &NullableTagCollectionData{value: val, isSet: true}
}

func (v NullableTagCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


