/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorCreate{}

// AuthorCreate struct for AuthorCreate
type AuthorCreate struct {
	Data AuthorCreateData `json:"data"`
}

type _AuthorCreate AuthorCreate

// NewAuthorCreate instantiates a new AuthorCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorCreate(data AuthorCreateData) *AuthorCreate {
	this := AuthorCreate{}
	this.Data = data
	return &this
}

// NewAuthorCreateWithDefaults instantiates a new AuthorCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorCreateWithDefaults() *AuthorCreate {
	this := AuthorCreate{}
	return &this
}

// GetData returns the Data field value
func (o *AuthorCreate) GetData() AuthorCreateData {
	if o == nil {
		var ret AuthorCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AuthorCreate) GetDataOk() (*AuthorCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AuthorCreate) SetData(v AuthorCreateData) {
	o.Data = v
}

func (o AuthorCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AuthorCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorCreate := _AuthorCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorCreate)

	if err != nil {
		return err
	}

	*o = AuthorCreate(varAuthorCreate)

	return err
}

type NullableAuthorCreate struct {
	value *AuthorCreate
	isSet bool
}

func (v NullableAuthorCreate) Get() *AuthorCreate {
	return v.value
}

func (v *NullableAuthorCreate) Set(val *AuthorCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorCreate(val *AuthorCreate) *NullableAuthorCreate {
	return &NullableAuthorCreate{value: val, isSet: true}
}

func (v NullableAuthorCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


