/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateArticleData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateArticleData{}

// CreateArticleData struct for CreateArticleData
type CreateArticleData struct {
	Type string `json:"type"`
	Attributes CreateArticleDataAttributes `json:"attributes"`
}

type _CreateArticleData CreateArticleData

// NewCreateArticleData instantiates a new CreateArticleData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateArticleData(type_ string, attributes CreateArticleDataAttributes) *CreateArticleData {
	this := CreateArticleData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateArticleDataWithDefaults instantiates a new CreateArticleData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateArticleDataWithDefaults() *CreateArticleData {
	this := CreateArticleData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateArticleData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateArticleData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateArticleData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateArticleData) GetAttributes() CreateArticleDataAttributes {
	if o == nil {
		var ret CreateArticleDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateArticleData) GetAttributesOk() (*CreateArticleDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateArticleData) SetAttributes(v CreateArticleDataAttributes) {
	o.Attributes = v
}

func (o CreateArticleData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateArticleData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateArticleData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateArticleData := _CreateArticleData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateArticleData)

	if err != nil {
		return err
	}

	*o = CreateArticleData(varCreateArticleData)

	return err
}

type NullableCreateArticleData struct {
	value *CreateArticleData
	isSet bool
}

func (v NullableCreateArticleData) Get() *CreateArticleData {
	return v.value
}

func (v *NullableCreateArticleData) Set(val *CreateArticleData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateArticleData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateArticleData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateArticleData(val *CreateArticleData) *NullableCreateArticleData {
	return &NullableCreateArticleData{value: val, isSet: true}
}

func (v NullableCreateArticleData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateArticleData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


