/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorsCollectionDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorsCollectionDataAttributes{}

// AuthorsCollectionDataAttributes struct for AuthorsCollectionDataAttributes
type AuthorsCollectionDataAttributes struct {
	Data []AuthorData `json:"data"`
}

type _AuthorsCollectionDataAttributes AuthorsCollectionDataAttributes

// NewAuthorsCollectionDataAttributes instantiates a new AuthorsCollectionDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorsCollectionDataAttributes(data []AuthorData) *AuthorsCollectionDataAttributes {
	this := AuthorsCollectionDataAttributes{}
	this.Data = data
	return &this
}

// NewAuthorsCollectionDataAttributesWithDefaults instantiates a new AuthorsCollectionDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorsCollectionDataAttributesWithDefaults() *AuthorsCollectionDataAttributes {
	this := AuthorsCollectionDataAttributes{}
	return &this
}

// GetData returns the Data field value
func (o *AuthorsCollectionDataAttributes) GetData() []AuthorData {
	if o == nil {
		var ret []AuthorData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AuthorsCollectionDataAttributes) GetDataOk() ([]AuthorData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AuthorsCollectionDataAttributes) SetData(v []AuthorData) {
	o.Data = v
}

func (o AuthorsCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorsCollectionDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AuthorsCollectionDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorsCollectionDataAttributes := _AuthorsCollectionDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorsCollectionDataAttributes)

	if err != nil {
		return err
	}

	*o = AuthorsCollectionDataAttributes(varAuthorsCollectionDataAttributes)

	return err
}

type NullableAuthorsCollectionDataAttributes struct {
	value *AuthorsCollectionDataAttributes
	isSet bool
}

func (v NullableAuthorsCollectionDataAttributes) Get() *AuthorsCollectionDataAttributes {
	return v.value
}

func (v *NullableAuthorsCollectionDataAttributes) Set(val *AuthorsCollectionDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorsCollectionDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorsCollectionDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorsCollectionDataAttributes(val *AuthorsCollectionDataAttributes) *NullableAuthorsCollectionDataAttributes {
	return &NullableAuthorsCollectionDataAttributes{value: val, isSet: true}
}

func (v NullableAuthorsCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorsCollectionDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


