/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTag{}

// CreateTag struct for CreateTag
type CreateTag struct {
	Data CreateTagData `json:"data"`
}

type _CreateTag CreateTag

// NewCreateTag instantiates a new CreateTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTag(data CreateTagData) *CreateTag {
	this := CreateTag{}
	this.Data = data
	return &this
}

// NewCreateTagWithDefaults instantiates a new CreateTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTagWithDefaults() *CreateTag {
	this := CreateTag{}
	return &this
}

// GetData returns the Data field value
func (o *CreateTag) GetData() CreateTagData {
	if o == nil {
		var ret CreateTagData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateTag) GetDataOk() (*CreateTagData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateTag) SetData(v CreateTagData) {
	o.Data = v
}

func (o CreateTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateTag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTag := _CreateTag{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTag)

	if err != nil {
		return err
	}

	*o = CreateTag(varCreateTag)

	return err
}

type NullableCreateTag struct {
	value *CreateTag
	isSet bool
}

func (v NullableCreateTag) Get() *CreateTag {
	return v.value
}

func (v *NullableCreateTag) Set(val *CreateTag) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTag) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTag(val *CreateTag) *NullableCreateTag {
	return &NullableCreateTag{value: val, isSet: true}
}

func (v NullableCreateTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


