/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorshipCreateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorshipCreateDataAttributes{}

// AuthorshipCreateDataAttributes struct for AuthorshipCreateDataAttributes
type AuthorshipCreateDataAttributes struct {
	AuthorID []string `json:"authorID,omitempty"`
	// The ID of the article.
	ArticleID string `json:"articleID"`
}

type _AuthorshipCreateDataAttributes AuthorshipCreateDataAttributes

// NewAuthorshipCreateDataAttributes instantiates a new AuthorshipCreateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorshipCreateDataAttributes(articleID string) *AuthorshipCreateDataAttributes {
	this := AuthorshipCreateDataAttributes{}
	this.ArticleID = articleID
	return &this
}

// NewAuthorshipCreateDataAttributesWithDefaults instantiates a new AuthorshipCreateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorshipCreateDataAttributesWithDefaults() *AuthorshipCreateDataAttributes {
	this := AuthorshipCreateDataAttributes{}
	return &this
}

// GetAuthorID returns the AuthorID field value if set, zero value otherwise.
func (o *AuthorshipCreateDataAttributes) GetAuthorID() []string {
	if o == nil || IsNil(o.AuthorID) {
		var ret []string
		return ret
	}
	return o.AuthorID
}

// GetAuthorIDOk returns a tuple with the AuthorID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorshipCreateDataAttributes) GetAuthorIDOk() ([]string, bool) {
	if o == nil || IsNil(o.AuthorID) {
		return nil, false
	}
	return o.AuthorID, true
}

// HasAuthorID returns a boolean if a field has been set.
func (o *AuthorshipCreateDataAttributes) HasAuthorID() bool {
	if o != nil && !IsNil(o.AuthorID) {
		return true
	}

	return false
}

// SetAuthorID gets a reference to the given []string and assigns it to the AuthorID field.
func (o *AuthorshipCreateDataAttributes) SetAuthorID(v []string) {
	o.AuthorID = v
}

// GetArticleID returns the ArticleID field value
func (o *AuthorshipCreateDataAttributes) GetArticleID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArticleID
}

// GetArticleIDOk returns a tuple with the ArticleID field value
// and a boolean to check if the value has been set.
func (o *AuthorshipCreateDataAttributes) GetArticleIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArticleID, true
}

// SetArticleID sets field value
func (o *AuthorshipCreateDataAttributes) SetArticleID(v string) {
	o.ArticleID = v
}

func (o AuthorshipCreateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorshipCreateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthorID) {
		toSerialize["authorID"] = o.AuthorID
	}
	toSerialize["articleID"] = o.ArticleID
	return toSerialize, nil
}

func (o *AuthorshipCreateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"articleID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorshipCreateDataAttributes := _AuthorshipCreateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorshipCreateDataAttributes)

	if err != nil {
		return err
	}

	*o = AuthorshipCreateDataAttributes(varAuthorshipCreateDataAttributes)

	return err
}

type NullableAuthorshipCreateDataAttributes struct {
	value *AuthorshipCreateDataAttributes
	isSet bool
}

func (v NullableAuthorshipCreateDataAttributes) Get() *AuthorshipCreateDataAttributes {
	return v.value
}

func (v *NullableAuthorshipCreateDataAttributes) Set(val *AuthorshipCreateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorshipCreateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorshipCreateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorshipCreateDataAttributes(val *AuthorshipCreateDataAttributes) *NullableAuthorshipCreateDataAttributes {
	return &NullableAuthorshipCreateDataAttributes{value: val, isSet: true}
}

func (v NullableAuthorshipCreateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorshipCreateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


