/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateArticleData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateArticleData{}

// UpdateArticleData struct for UpdateArticleData
type UpdateArticleData struct {
	// Article ID uuid
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes UpdateArticleDataAttributes `json:"attributes"`
}

type _UpdateArticleData UpdateArticleData

// NewUpdateArticleData instantiates a new UpdateArticleData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateArticleData(id string, type_ string, attributes UpdateArticleDataAttributes) *UpdateArticleData {
	this := UpdateArticleData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateArticleDataWithDefaults instantiates a new UpdateArticleData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateArticleDataWithDefaults() *UpdateArticleData {
	this := UpdateArticleData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateArticleData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateArticleData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateArticleData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateArticleData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateArticleData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateArticleData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateArticleData) GetAttributes() UpdateArticleDataAttributes {
	if o == nil {
		var ret UpdateArticleDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateArticleData) GetAttributesOk() (*UpdateArticleDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateArticleData) SetAttributes(v UpdateArticleDataAttributes) {
	o.Attributes = v
}

func (o UpdateArticleData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateArticleData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateArticleData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateArticleData := _UpdateArticleData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateArticleData)

	if err != nil {
		return err
	}

	*o = UpdateArticleData(varUpdateArticleData)

	return err
}

type NullableUpdateArticleData struct {
	value *UpdateArticleData
	isSet bool
}

func (v NullableUpdateArticleData) Get() *UpdateArticleData {
	return v.value
}

func (v *NullableUpdateArticleData) Set(val *UpdateArticleData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateArticleData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateArticleData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateArticleData(val *UpdateArticleData) *NullableUpdateArticleData {
	return &NullableUpdateArticleData{value: val, isSet: true}
}

func (v NullableUpdateArticleData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateArticleData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


