/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleData{}

// ArticleData struct for ArticleData
type ArticleData struct {
	// article ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes ArticleAttributes `json:"attributes"`
}

type _ArticleData ArticleData

// NewArticleData instantiates a new ArticleData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleData(id string, type_ string, attributes ArticleAttributes) *ArticleData {
	this := ArticleData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewArticleDataWithDefaults instantiates a new ArticleData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleDataWithDefaults() *ArticleData {
	this := ArticleData{}
	return &this
}

// GetId returns the Id field value
func (o *ArticleData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ArticleData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ArticleData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ArticleData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ArticleData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ArticleData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ArticleData) GetAttributes() ArticleAttributes {
	if o == nil {
		var ret ArticleAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ArticleData) GetAttributesOk() (*ArticleAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ArticleData) SetAttributes(v ArticleAttributes) {
	o.Attributes = v
}

func (o ArticleData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ArticleData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleData := _ArticleData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleData)

	if err != nil {
		return err
	}

	*o = ArticleData(varArticleData)

	return err
}

type NullableArticleData struct {
	value *ArticleData
	isSet bool
}

func (v NullableArticleData) Get() *ArticleData {
	return v.value
}

func (v *NullableArticleData) Set(val *ArticleData) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleData) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleData(val *ArticleData) *NullableArticleData {
	return &NullableArticleData{value: val, isSet: true}
}

func (v NullableArticleData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


