/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleShortCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleShortCollectionData{}

// ArticleShortCollectionData struct for ArticleShortCollectionData
type ArticleShortCollectionData struct {
	Type string `json:"type"`
	Attributes ArticleShortCollectionDataAttributes `json:"attributes"`
}

type _ArticleShortCollectionData ArticleShortCollectionData

// NewArticleShortCollectionData instantiates a new ArticleShortCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleShortCollectionData(type_ string, attributes ArticleShortCollectionDataAttributes) *ArticleShortCollectionData {
	this := ArticleShortCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewArticleShortCollectionDataWithDefaults instantiates a new ArticleShortCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleShortCollectionDataWithDefaults() *ArticleShortCollectionData {
	this := ArticleShortCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *ArticleShortCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ArticleShortCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ArticleShortCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ArticleShortCollectionData) GetAttributes() ArticleShortCollectionDataAttributes {
	if o == nil {
		var ret ArticleShortCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ArticleShortCollectionData) GetAttributesOk() (*ArticleShortCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ArticleShortCollectionData) SetAttributes(v ArticleShortCollectionDataAttributes) {
	o.Attributes = v
}

func (o ArticleShortCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleShortCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ArticleShortCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleShortCollectionData := _ArticleShortCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleShortCollectionData)

	if err != nil {
		return err
	}

	*o = ArticleShortCollectionData(varArticleShortCollectionData)

	return err
}

type NullableArticleShortCollectionData struct {
	value *ArticleShortCollectionData
	isSet bool
}

func (v NullableArticleShortCollectionData) Get() *ArticleShortCollectionData {
	return v.value
}

func (v *NullableArticleShortCollectionData) Set(val *ArticleShortCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleShortCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleShortCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleShortCollectionData(val *ArticleShortCollectionData) *NullableArticleShortCollectionData {
	return &NullableArticleShortCollectionData{value: val, isSet: true}
}

func (v NullableArticleShortCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleShortCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


