/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorshipCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorshipCreate{}

// AuthorshipCreate struct for AuthorshipCreate
type AuthorshipCreate struct {
	Data AuthorshipCreateData `json:"data"`
}

type _AuthorshipCreate AuthorshipCreate

// NewAuthorshipCreate instantiates a new AuthorshipCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorshipCreate(data AuthorshipCreateData) *AuthorshipCreate {
	this := AuthorshipCreate{}
	this.Data = data
	return &this
}

// NewAuthorshipCreateWithDefaults instantiates a new AuthorshipCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorshipCreateWithDefaults() *AuthorshipCreate {
	this := AuthorshipCreate{}
	return &this
}

// GetData returns the Data field value
func (o *AuthorshipCreate) GetData() AuthorshipCreateData {
	if o == nil {
		var ret AuthorshipCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AuthorshipCreate) GetDataOk() (*AuthorshipCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AuthorshipCreate) SetData(v AuthorshipCreateData) {
	o.Data = v
}

func (o AuthorshipCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorshipCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AuthorshipCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorshipCreate := _AuthorshipCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorshipCreate)

	if err != nil {
		return err
	}

	*o = AuthorshipCreate(varAuthorshipCreate)

	return err
}

type NullableAuthorshipCreate struct {
	value *AuthorshipCreate
	isSet bool
}

func (v NullableAuthorshipCreate) Get() *AuthorshipCreate {
	return v.value
}

func (v *NullableAuthorshipCreate) Set(val *AuthorshipCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorshipCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorshipCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorshipCreate(val *AuthorshipCreate) *NullableAuthorshipCreate {
	return &NullableAuthorshipCreate{value: val, isSet: true}
}

func (v NullableAuthorshipCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorshipCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


