/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateArticleContentData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateArticleContentData{}

// UpdateArticleContentData struct for UpdateArticleContentData
type UpdateArticleContentData struct {
	// Article ID uuid
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes UpdateArticleContentDataAttributes `json:"attributes"`
}

type _UpdateArticleContentData UpdateArticleContentData

// NewUpdateArticleContentData instantiates a new UpdateArticleContentData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateArticleContentData(id string, type_ string, attributes UpdateArticleContentDataAttributes) *UpdateArticleContentData {
	this := UpdateArticleContentData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateArticleContentDataWithDefaults instantiates a new UpdateArticleContentData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateArticleContentDataWithDefaults() *UpdateArticleContentData {
	this := UpdateArticleContentData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateArticleContentData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateArticleContentData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateArticleContentData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateArticleContentData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateArticleContentData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateArticleContentData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateArticleContentData) GetAttributes() UpdateArticleContentDataAttributes {
	if o == nil {
		var ret UpdateArticleContentDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateArticleContentData) GetAttributesOk() (*UpdateArticleContentDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateArticleContentData) SetAttributes(v UpdateArticleContentDataAttributes) {
	o.Attributes = v
}

func (o UpdateArticleContentData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateArticleContentData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateArticleContentData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateArticleContentData := _UpdateArticleContentData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateArticleContentData)

	if err != nil {
		return err
	}

	*o = UpdateArticleContentData(varUpdateArticleContentData)

	return err
}

type NullableUpdateArticleContentData struct {
	value *UpdateArticleContentData
	isSet bool
}

func (v NullableUpdateArticleContentData) Get() *UpdateArticleContentData {
	return v.value
}

func (v *NullableUpdateArticleContentData) Set(val *UpdateArticleContentData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateArticleContentData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateArticleContentData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateArticleContentData(val *UpdateArticleContentData) *NullableUpdateArticleContentData {
	return &NullableUpdateArticleContentData{value: val, isSet: true}
}

func (v NullableUpdateArticleContentData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateArticleContentData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


