/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateTagData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTagData{}

// UpdateTagData struct for UpdateTagData
type UpdateTagData struct {
	// tag id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes UpdateTagDataAttributes `json:"attributes"`
}

type _UpdateTagData UpdateTagData

// NewUpdateTagData instantiates a new UpdateTagData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTagData(id string, type_ string, attributes UpdateTagDataAttributes) *UpdateTagData {
	this := UpdateTagData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateTagDataWithDefaults instantiates a new UpdateTagData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTagDataWithDefaults() *UpdateTagData {
	this := UpdateTagData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateTagData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateTagData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateTagData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateTagData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateTagData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateTagData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateTagData) GetAttributes() UpdateTagDataAttributes {
	if o == nil {
		var ret UpdateTagDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateTagData) GetAttributesOk() (*UpdateTagDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateTagData) SetAttributes(v UpdateTagDataAttributes) {
	o.Attributes = v
}

func (o UpdateTagData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTagData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateTagData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTagData := _UpdateTagData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTagData)

	if err != nil {
		return err
	}

	*o = UpdateTagData(varUpdateTagData)

	return err
}

type NullableUpdateTagData struct {
	value *UpdateTagData
	isSet bool
}

func (v NullableUpdateTagData) Get() *UpdateTagData {
	return v.value
}

func (v *NullableUpdateTagData) Set(val *UpdateTagData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTagData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTagData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTagData(val *UpdateTagData) *NullableUpdateTagData {
	return &NullableUpdateTagData{value: val, isSet: true}
}

func (v NullableUpdateTagData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTagData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


