/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetAuthorship type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetAuthorship{}

// SetAuthorship struct for SetAuthorship
type SetAuthorship struct {
	Data SetAuthorshipData `json:"data"`
}

type _SetAuthorship SetAuthorship

// NewSetAuthorship instantiates a new SetAuthorship object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetAuthorship(data SetAuthorshipData) *SetAuthorship {
	this := SetAuthorship{}
	this.Data = data
	return &this
}

// NewSetAuthorshipWithDefaults instantiates a new SetAuthorship object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetAuthorshipWithDefaults() *SetAuthorship {
	this := SetAuthorship{}
	return &this
}

// GetData returns the Data field value
func (o *SetAuthorship) GetData() SetAuthorshipData {
	if o == nil {
		var ret SetAuthorshipData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SetAuthorship) GetDataOk() (*SetAuthorshipData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SetAuthorship) SetData(v SetAuthorshipData) {
	o.Data = v
}

func (o SetAuthorship) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetAuthorship) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SetAuthorship) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetAuthorship := _SetAuthorship{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetAuthorship)

	if err != nil {
		return err
	}

	*o = SetAuthorship(varSetAuthorship)

	return err
}

type NullableSetAuthorship struct {
	value *SetAuthorship
	isSet bool
}

func (v NullableSetAuthorship) Get() *SetAuthorship {
	return v.value
}

func (v *NullableSetAuthorship) Set(val *SetAuthorship) {
	v.value = val
	v.isSet = true
}

func (v NullableSetAuthorship) IsSet() bool {
	return v.isSet
}

func (v *NullableSetAuthorship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetAuthorship(val *SetAuthorship) *NullableSetAuthorship {
	return &NullableSetAuthorship{value: val, isSet: true}
}

func (v NullableSetAuthorship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetAuthorship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


