/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SectionMediaInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SectionMediaInner{}

// SectionMediaInner struct for SectionMediaInner
type SectionMediaInner struct {
	Url string `json:"url"`
	Caption string `json:"caption"`
	Alt string `json:"alt"`
	Width int32 `json:"width"`
	Height int32 `json:"height"`
	Source string `json:"source"`
}

type _SectionMediaInner SectionMediaInner

// NewSectionMediaInner instantiates a new SectionMediaInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSectionMediaInner(url string, caption string, alt string, width int32, height int32, source string) *SectionMediaInner {
	this := SectionMediaInner{}
	this.Url = url
	this.Caption = caption
	this.Alt = alt
	this.Width = width
	this.Height = height
	this.Source = source
	return &this
}

// NewSectionMediaInnerWithDefaults instantiates a new SectionMediaInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSectionMediaInnerWithDefaults() *SectionMediaInner {
	this := SectionMediaInner{}
	return &this
}

// GetUrl returns the Url field value
func (o *SectionMediaInner) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *SectionMediaInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *SectionMediaInner) SetUrl(v string) {
	o.Url = v
}

// GetCaption returns the Caption field value
func (o *SectionMediaInner) GetCaption() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Caption
}

// GetCaptionOk returns a tuple with the Caption field value
// and a boolean to check if the value has been set.
func (o *SectionMediaInner) GetCaptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Caption, true
}

// SetCaption sets field value
func (o *SectionMediaInner) SetCaption(v string) {
	o.Caption = v
}

// GetAlt returns the Alt field value
func (o *SectionMediaInner) GetAlt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Alt
}

// GetAltOk returns a tuple with the Alt field value
// and a boolean to check if the value has been set.
func (o *SectionMediaInner) GetAltOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alt, true
}

// SetAlt sets field value
func (o *SectionMediaInner) SetAlt(v string) {
	o.Alt = v
}

// GetWidth returns the Width field value
func (o *SectionMediaInner) GetWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *SectionMediaInner) GetWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *SectionMediaInner) SetWidth(v int32) {
	o.Width = v
}

// GetHeight returns the Height field value
func (o *SectionMediaInner) GetHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *SectionMediaInner) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *SectionMediaInner) SetHeight(v int32) {
	o.Height = v
}

// GetSource returns the Source field value
func (o *SectionMediaInner) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *SectionMediaInner) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *SectionMediaInner) SetSource(v string) {
	o.Source = v
}

func (o SectionMediaInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SectionMediaInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["caption"] = o.Caption
	toSerialize["alt"] = o.Alt
	toSerialize["width"] = o.Width
	toSerialize["height"] = o.Height
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *SectionMediaInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"caption",
		"alt",
		"width",
		"height",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSectionMediaInner := _SectionMediaInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSectionMediaInner)

	if err != nil {
		return err
	}

	*o = SectionMediaInner(varSectionMediaInner)

	return err
}

type NullableSectionMediaInner struct {
	value *SectionMediaInner
	isSet bool
}

func (v NullableSectionMediaInner) Get() *SectionMediaInner {
	return v.value
}

func (v *NullableSectionMediaInner) Set(val *SectionMediaInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSectionMediaInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSectionMediaInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSectionMediaInner(val *SectionMediaInner) *NullableSectionMediaInner {
	return &NullableSectionMediaInner{value: val, isSet: true}
}

func (v NullableSectionMediaInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSectionMediaInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


