/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContentUpdateResponseDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentUpdateResponseDataAttributes{}

// ContentUpdateResponseDataAttributes struct for ContentUpdateResponseDataAttributes
type ContentUpdateResponseDataAttributes struct {
	// The status of the content update operation.
	Status string `json:"status"`
	// A message providing additional information about the operation.
	Message string `json:"message"`
	SectionNumber int32 `json:"section_number"`
	Content *Content `json:"content,omitempty"`
}

type _ContentUpdateResponseDataAttributes ContentUpdateResponseDataAttributes

// NewContentUpdateResponseDataAttributes instantiates a new ContentUpdateResponseDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentUpdateResponseDataAttributes(status string, message string, sectionNumber int32) *ContentUpdateResponseDataAttributes {
	this := ContentUpdateResponseDataAttributes{}
	this.Status = status
	this.Message = message
	this.SectionNumber = sectionNumber
	return &this
}

// NewContentUpdateResponseDataAttributesWithDefaults instantiates a new ContentUpdateResponseDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentUpdateResponseDataAttributesWithDefaults() *ContentUpdateResponseDataAttributes {
	this := ContentUpdateResponseDataAttributes{}
	return &this
}

// GetStatus returns the Status field value
func (o *ContentUpdateResponseDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ContentUpdateResponseDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ContentUpdateResponseDataAttributes) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *ContentUpdateResponseDataAttributes) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ContentUpdateResponseDataAttributes) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ContentUpdateResponseDataAttributes) SetMessage(v string) {
	o.Message = v
}

// GetSectionNumber returns the SectionNumber field value
func (o *ContentUpdateResponseDataAttributes) GetSectionNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SectionNumber
}

// GetSectionNumberOk returns a tuple with the SectionNumber field value
// and a boolean to check if the value has been set.
func (o *ContentUpdateResponseDataAttributes) GetSectionNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SectionNumber, true
}

// SetSectionNumber sets field value
func (o *ContentUpdateResponseDataAttributes) SetSectionNumber(v int32) {
	o.SectionNumber = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *ContentUpdateResponseDataAttributes) GetContent() Content {
	if o == nil || IsNil(o.Content) {
		var ret Content
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentUpdateResponseDataAttributes) GetContentOk() (*Content, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *ContentUpdateResponseDataAttributes) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given Content and assigns it to the Content field.
func (o *ContentUpdateResponseDataAttributes) SetContent(v Content) {
	o.Content = &v
}

func (o ContentUpdateResponseDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentUpdateResponseDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["section_number"] = o.SectionNumber
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

func (o *ContentUpdateResponseDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"message",
		"section_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentUpdateResponseDataAttributes := _ContentUpdateResponseDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContentUpdateResponseDataAttributes)

	if err != nil {
		return err
	}

	*o = ContentUpdateResponseDataAttributes(varContentUpdateResponseDataAttributes)

	return err
}

type NullableContentUpdateResponseDataAttributes struct {
	value *ContentUpdateResponseDataAttributes
	isSet bool
}

func (v NullableContentUpdateResponseDataAttributes) Get() *ContentUpdateResponseDataAttributes {
	return v.value
}

func (v *NullableContentUpdateResponseDataAttributes) Set(val *ContentUpdateResponseDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableContentUpdateResponseDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableContentUpdateResponseDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentUpdateResponseDataAttributes(val *ContentUpdateResponseDataAttributes) *NullableContentUpdateResponseDataAttributes {
	return &NullableContentUpdateResponseDataAttributes{value: val, isSet: true}
}

func (v NullableContentUpdateResponseDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentUpdateResponseDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


