/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleShortData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleShortData{}

// ArticleShortData struct for ArticleShortData
type ArticleShortData struct {
	// article ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes ArticleShortDataAttributes `json:"attributes"`
	Relationships *ArticleShortDataRelationships `json:"relationships,omitempty"`
}

type _ArticleShortData ArticleShortData

// NewArticleShortData instantiates a new ArticleShortData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleShortData(id string, type_ string, attributes ArticleShortDataAttributes) *ArticleShortData {
	this := ArticleShortData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewArticleShortDataWithDefaults instantiates a new ArticleShortData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleShortDataWithDefaults() *ArticleShortData {
	this := ArticleShortData{}
	return &this
}

// GetId returns the Id field value
func (o *ArticleShortData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ArticleShortData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ArticleShortData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ArticleShortData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ArticleShortData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ArticleShortData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ArticleShortData) GetAttributes() ArticleShortDataAttributes {
	if o == nil {
		var ret ArticleShortDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ArticleShortData) GetAttributesOk() (*ArticleShortDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ArticleShortData) SetAttributes(v ArticleShortDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *ArticleShortData) GetRelationships() ArticleShortDataRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret ArticleShortDataRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleShortData) GetRelationshipsOk() (*ArticleShortDataRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *ArticleShortData) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given ArticleShortDataRelationships and assigns it to the Relationships field.
func (o *ArticleShortData) SetRelationships(v ArticleShortDataRelationships) {
	o.Relationships = &v
}

func (o ArticleShortData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleShortData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

func (o *ArticleShortData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleShortData := _ArticleShortData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleShortData)

	if err != nil {
		return err
	}

	*o = ArticleShortData(varArticleShortData)

	return err
}

type NullableArticleShortData struct {
	value *ArticleShortData
	isSet bool
}

func (v NullableArticleShortData) Get() *ArticleShortData {
	return v.value
}

func (v *NullableArticleShortData) Set(val *ArticleShortData) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleShortData) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleShortData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleShortData(val *ArticleShortData) *NullableArticleShortData {
	return &NullableArticleShortData{value: val, isSet: true}
}

func (v NullableArticleShortData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleShortData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


