/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAuthorDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAuthorDataAttributes{}

// CreateAuthorDataAttributes struct for CreateAuthorDataAttributes
type CreateAuthorDataAttributes struct {
	Name string `json:"name"`
}

type _CreateAuthorDataAttributes CreateAuthorDataAttributes

// NewCreateAuthorDataAttributes instantiates a new CreateAuthorDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAuthorDataAttributes(name string) *CreateAuthorDataAttributes {
	this := CreateAuthorDataAttributes{}
	this.Name = name
	return &this
}

// NewCreateAuthorDataAttributesWithDefaults instantiates a new CreateAuthorDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAuthorDataAttributesWithDefaults() *CreateAuthorDataAttributes {
	this := CreateAuthorDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAuthorDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAuthorDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAuthorDataAttributes) SetName(v string) {
	o.Name = v
}

func (o CreateAuthorDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAuthorDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateAuthorDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAuthorDataAttributes := _CreateAuthorDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAuthorDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateAuthorDataAttributes(varCreateAuthorDataAttributes)

	return err
}

type NullableCreateAuthorDataAttributes struct {
	value *CreateAuthorDataAttributes
	isSet bool
}

func (v NullableCreateAuthorDataAttributes) Get() *CreateAuthorDataAttributes {
	return v.value
}

func (v *NullableCreateAuthorDataAttributes) Set(val *CreateAuthorDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAuthorDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAuthorDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAuthorDataAttributes(val *CreateAuthorDataAttributes) *NullableCreateAuthorDataAttributes {
	return &NullableCreateAuthorDataAttributes{value: val, isSet: true}
}

func (v NullableCreateAuthorDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAuthorDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


