/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateArticle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateArticle{}

// UpdateArticle struct for UpdateArticle
type UpdateArticle struct {
	Data UpdateArticleData `json:"data"`
}

type _UpdateArticle UpdateArticle

// NewUpdateArticle instantiates a new UpdateArticle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateArticle(data UpdateArticleData) *UpdateArticle {
	this := UpdateArticle{}
	this.Data = data
	return &this
}

// NewUpdateArticleWithDefaults instantiates a new UpdateArticle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateArticleWithDefaults() *UpdateArticle {
	this := UpdateArticle{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateArticle) GetData() UpdateArticleData {
	if o == nil {
		var ret UpdateArticleData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateArticle) GetDataOk() (*UpdateArticleData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateArticle) SetData(v UpdateArticleData) {
	o.Data = v
}

func (o UpdateArticle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateArticle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateArticle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateArticle := _UpdateArticle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateArticle)

	if err != nil {
		return err
	}

	*o = UpdateArticle(varUpdateArticle)

	return err
}

type NullableUpdateArticle struct {
	value *UpdateArticle
	isSet bool
}

func (v NullableUpdateArticle) Get() *UpdateArticle {
	return v.value
}

func (v *NullableUpdateArticle) Set(val *UpdateArticle) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateArticle) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateArticle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateArticle(val *UpdateArticle) *NullableUpdateArticle {
	return &NullableUpdateArticle{value: val, isSet: true}
}

func (v NullableUpdateArticle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateArticle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


