/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetAuthorshipData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetAuthorshipData{}

// SetAuthorshipData struct for SetAuthorshipData
type SetAuthorshipData struct {
	// The ID of the article set.
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes SetAuthorshipDataAttributes `json:"attributes"`
}

type _SetAuthorshipData SetAuthorshipData

// NewSetAuthorshipData instantiates a new SetAuthorshipData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetAuthorshipData(id string, type_ string, attributes SetAuthorshipDataAttributes) *SetAuthorshipData {
	this := SetAuthorshipData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSetAuthorshipDataWithDefaults instantiates a new SetAuthorshipData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetAuthorshipDataWithDefaults() *SetAuthorshipData {
	this := SetAuthorshipData{}
	return &this
}

// GetId returns the Id field value
func (o *SetAuthorshipData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SetAuthorshipData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SetAuthorshipData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SetAuthorshipData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SetAuthorshipData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SetAuthorshipData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SetAuthorshipData) GetAttributes() SetAuthorshipDataAttributes {
	if o == nil {
		var ret SetAuthorshipDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SetAuthorshipData) GetAttributesOk() (*SetAuthorshipDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SetAuthorshipData) SetAttributes(v SetAuthorshipDataAttributes) {
	o.Attributes = v
}

func (o SetAuthorshipData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetAuthorshipData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SetAuthorshipData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetAuthorshipData := _SetAuthorshipData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetAuthorshipData)

	if err != nil {
		return err
	}

	*o = SetAuthorshipData(varSetAuthorshipData)

	return err
}

type NullableSetAuthorshipData struct {
	value *SetAuthorshipData
	isSet bool
}

func (v NullableSetAuthorshipData) Get() *SetAuthorshipData {
	return v.value
}

func (v *NullableSetAuthorshipData) Set(val *SetAuthorshipData) {
	v.value = val
	v.isSet = true
}

func (v NullableSetAuthorshipData) IsSet() bool {
	return v.isSet
}

func (v *NullableSetAuthorshipData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetAuthorshipData(val *SetAuthorshipData) *NullableSetAuthorshipData {
	return &NullableSetAuthorshipData{value: val, isSet: true}
}

func (v NullableSetAuthorshipData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetAuthorshipData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


