/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorUpdate{}

// AuthorUpdate struct for AuthorUpdate
type AuthorUpdate struct {
	Data AuthorUpdateData `json:"data"`
}

type _AuthorUpdate AuthorUpdate

// NewAuthorUpdate instantiates a new AuthorUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorUpdate(data AuthorUpdateData) *AuthorUpdate {
	this := AuthorUpdate{}
	this.Data = data
	return &this
}

// NewAuthorUpdateWithDefaults instantiates a new AuthorUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorUpdateWithDefaults() *AuthorUpdate {
	this := AuthorUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *AuthorUpdate) GetData() AuthorUpdateData {
	if o == nil {
		var ret AuthorUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AuthorUpdate) GetDataOk() (*AuthorUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AuthorUpdate) SetData(v AuthorUpdateData) {
	o.Data = v
}

func (o AuthorUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AuthorUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorUpdate := _AuthorUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorUpdate)

	if err != nil {
		return err
	}

	*o = AuthorUpdate(varAuthorUpdate)

	return err
}

type NullableAuthorUpdate struct {
	value *AuthorUpdate
	isSet bool
}

func (v NullableAuthorUpdate) Get() *AuthorUpdate {
	return v.value
}

func (v *NullableAuthorUpdate) Set(val *AuthorUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorUpdate(val *AuthorUpdate) *NullableAuthorUpdate {
	return &NullableAuthorUpdate{value: val, isSet: true}
}

func (v NullableAuthorUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


