/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagCreateData{}

// TagCreateData struct for TagCreateData
type TagCreateData struct {
	Type string `json:"type"`
	Attributes TagCreateDataAttributes `json:"attributes"`
}

type _TagCreateData TagCreateData

// NewTagCreateData instantiates a new TagCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagCreateData(type_ string, attributes TagCreateDataAttributes) *TagCreateData {
	this := TagCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewTagCreateDataWithDefaults instantiates a new TagCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagCreateDataWithDefaults() *TagCreateData {
	this := TagCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *TagCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TagCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TagCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *TagCreateData) GetAttributes() TagCreateDataAttributes {
	if o == nil {
		var ret TagCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *TagCreateData) GetAttributesOk() (*TagCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *TagCreateData) SetAttributes(v TagCreateDataAttributes) {
	o.Attributes = v
}

func (o TagCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *TagCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagCreateData := _TagCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagCreateData)

	if err != nil {
		return err
	}

	*o = TagCreateData(varTagCreateData)

	return err
}

type NullableTagCreateData struct {
	value *TagCreateData
	isSet bool
}

func (v NullableTagCreateData) Get() *TagCreateData {
	return v.value
}

func (v *NullableTagCreateData) Set(val *TagCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableTagCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableTagCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagCreateData(val *TagCreateData) *NullableTagCreateData {
	return &NullableTagCreateData{value: val, isSet: true}
}

func (v NullableTagCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


