/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the SectionTextInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SectionTextInner{}

// SectionTextInner struct for SectionTextInner
type SectionTextInner struct {
	Text *string `json:"text,omitempty"`
}

// NewSectionTextInner instantiates a new SectionTextInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSectionTextInner() *SectionTextInner {
	this := SectionTextInner{}
	return &this
}

// NewSectionTextInnerWithDefaults instantiates a new SectionTextInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSectionTextInnerWithDefaults() *SectionTextInner {
	this := SectionTextInner{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *SectionTextInner) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SectionTextInner) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *SectionTextInner) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *SectionTextInner) SetText(v string) {
	o.Text = &v
}

func (o SectionTextInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SectionTextInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableSectionTextInner struct {
	value *SectionTextInner
	isSet bool
}

func (v NullableSectionTextInner) Get() *SectionTextInner {
	return v.value
}

func (v *NullableSectionTextInner) Set(val *SectionTextInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSectionTextInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSectionTextInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSectionTextInner(val *SectionTextInner) *NullableSectionTextInner {
	return &NullableSectionTextInner{value: val, isSet: true}
}

func (v NullableSectionTextInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSectionTextInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


