/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContentUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentUpdateResponse{}

// ContentUpdateResponse struct for ContentUpdateResponse
type ContentUpdateResponse struct {
	Data ContentUpdateResponseData `json:"data"`
}

type _ContentUpdateResponse ContentUpdateResponse

// NewContentUpdateResponse instantiates a new ContentUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentUpdateResponse(data ContentUpdateResponseData) *ContentUpdateResponse {
	this := ContentUpdateResponse{}
	this.Data = data
	return &this
}

// NewContentUpdateResponseWithDefaults instantiates a new ContentUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentUpdateResponseWithDefaults() *ContentUpdateResponse {
	this := ContentUpdateResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ContentUpdateResponse) GetData() ContentUpdateResponseData {
	if o == nil {
		var ret ContentUpdateResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ContentUpdateResponse) GetDataOk() (*ContentUpdateResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ContentUpdateResponse) SetData(v ContentUpdateResponseData) {
	o.Data = v
}

func (o ContentUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ContentUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentUpdateResponse := _ContentUpdateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContentUpdateResponse)

	if err != nil {
		return err
	}

	*o = ContentUpdateResponse(varContentUpdateResponse)

	return err
}

type NullableContentUpdateResponse struct {
	value *ContentUpdateResponse
	isSet bool
}

func (v NullableContentUpdateResponse) Get() *ContentUpdateResponse {
	return v.value
}

func (v *NullableContentUpdateResponse) Set(val *ContentUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContentUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContentUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentUpdateResponse(val *ContentUpdateResponse) *NullableContentUpdateResponse {
	return &NullableContentUpdateResponse{value: val, isSet: true}
}

func (v NullableContentUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


