/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagCollectionDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagCollectionDataAttributes{}

// TagCollectionDataAttributes struct for TagCollectionDataAttributes
type TagCollectionDataAttributes struct {
	Data []TagData `json:"data"`
}

type _TagCollectionDataAttributes TagCollectionDataAttributes

// NewTagCollectionDataAttributes instantiates a new TagCollectionDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagCollectionDataAttributes(data []TagData) *TagCollectionDataAttributes {
	this := TagCollectionDataAttributes{}
	this.Data = data
	return &this
}

// NewTagCollectionDataAttributesWithDefaults instantiates a new TagCollectionDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagCollectionDataAttributesWithDefaults() *TagCollectionDataAttributes {
	this := TagCollectionDataAttributes{}
	return &this
}

// GetData returns the Data field value
func (o *TagCollectionDataAttributes) GetData() []TagData {
	if o == nil {
		var ret []TagData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TagCollectionDataAttributes) GetDataOk() ([]TagData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *TagCollectionDataAttributes) SetData(v []TagData) {
	o.Data = v
}

func (o TagCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagCollectionDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *TagCollectionDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagCollectionDataAttributes := _TagCollectionDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagCollectionDataAttributes)

	if err != nil {
		return err
	}

	*o = TagCollectionDataAttributes(varTagCollectionDataAttributes)

	return err
}

type NullableTagCollectionDataAttributes struct {
	value *TagCollectionDataAttributes
	isSet bool
}

func (v NullableTagCollectionDataAttributes) Get() *TagCollectionDataAttributes {
	return v.value
}

func (v *NullableTagCollectionDataAttributes) Set(val *TagCollectionDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableTagCollectionDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableTagCollectionDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagCollectionDataAttributes(val *TagCollectionDataAttributes) *NullableTagCollectionDataAttributes {
	return &NullableTagCollectionDataAttributes{value: val, isSet: true}
}

func (v NullableTagCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagCollectionDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


