/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleCreateData{}

// ArticleCreateData struct for ArticleCreateData
type ArticleCreateData struct {
	Type string `json:"type"`
	Attributes ArticleCreateDataAttributes `json:"attributes"`
}

type _ArticleCreateData ArticleCreateData

// NewArticleCreateData instantiates a new ArticleCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleCreateData(type_ string, attributes ArticleCreateDataAttributes) *ArticleCreateData {
	this := ArticleCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewArticleCreateDataWithDefaults instantiates a new ArticleCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleCreateDataWithDefaults() *ArticleCreateData {
	this := ArticleCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *ArticleCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ArticleCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ArticleCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ArticleCreateData) GetAttributes() ArticleCreateDataAttributes {
	if o == nil {
		var ret ArticleCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ArticleCreateData) GetAttributesOk() (*ArticleCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ArticleCreateData) SetAttributes(v ArticleCreateDataAttributes) {
	o.Attributes = v
}

func (o ArticleCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ArticleCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleCreateData := _ArticleCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleCreateData)

	if err != nil {
		return err
	}

	*o = ArticleCreateData(varArticleCreateData)

	return err
}

type NullableArticleCreateData struct {
	value *ArticleCreateData
	isSet bool
}

func (v NullableArticleCreateData) Get() *ArticleCreateData {
	return v.value
}

func (v *NullableArticleCreateData) Set(val *ArticleCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleCreateData(val *ArticleCreateData) *NullableArticleCreateData {
	return &NullableArticleCreateData{value: val, isSet: true}
}

func (v NullableArticleCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


