/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleUpdate{}

// ArticleUpdate struct for ArticleUpdate
type ArticleUpdate struct {
	Data ArticleUpdateData `json:"data"`
}

type _ArticleUpdate ArticleUpdate

// NewArticleUpdate instantiates a new ArticleUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleUpdate(data ArticleUpdateData) *ArticleUpdate {
	this := ArticleUpdate{}
	this.Data = data
	return &this
}

// NewArticleUpdateWithDefaults instantiates a new ArticleUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleUpdateWithDefaults() *ArticleUpdate {
	this := ArticleUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *ArticleUpdate) GetData() ArticleUpdateData {
	if o == nil {
		var ret ArticleUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ArticleUpdate) GetDataOk() (*ArticleUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ArticleUpdate) SetData(v ArticleUpdateData) {
	o.Data = v
}

func (o ArticleUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ArticleUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleUpdate := _ArticleUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleUpdate)

	if err != nil {
		return err
	}

	*o = ArticleUpdate(varArticleUpdate)

	return err
}

type NullableArticleUpdate struct {
	value *ArticleUpdate
	isSet bool
}

func (v NullableArticleUpdate) Get() *ArticleUpdate {
	return v.value
}

func (v *NullableArticleUpdate) Set(val *ArticleUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleUpdate(val *ArticleUpdate) *NullableArticleUpdate {
	return &NullableArticleUpdate{value: val, isSet: true}
}

func (v NullableArticleUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


