/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorshipCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorshipCreateData{}

// AuthorshipCreateData struct for AuthorshipCreateData
type AuthorshipCreateData struct {
	Type string `json:"type"`
	Attributes AuthorshipCreateDataAttributes `json:"attributes"`
}

type _AuthorshipCreateData AuthorshipCreateData

// NewAuthorshipCreateData instantiates a new AuthorshipCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorshipCreateData(type_ string, attributes AuthorshipCreateDataAttributes) *AuthorshipCreateData {
	this := AuthorshipCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAuthorshipCreateDataWithDefaults instantiates a new AuthorshipCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorshipCreateDataWithDefaults() *AuthorshipCreateData {
	this := AuthorshipCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *AuthorshipCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AuthorshipCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AuthorshipCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AuthorshipCreateData) GetAttributes() AuthorshipCreateDataAttributes {
	if o == nil {
		var ret AuthorshipCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AuthorshipCreateData) GetAttributesOk() (*AuthorshipCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AuthorshipCreateData) SetAttributes(v AuthorshipCreateDataAttributes) {
	o.Attributes = v
}

func (o AuthorshipCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorshipCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *AuthorshipCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorshipCreateData := _AuthorshipCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorshipCreateData)

	if err != nil {
		return err
	}

	*o = AuthorshipCreateData(varAuthorshipCreateData)

	return err
}

type NullableAuthorshipCreateData struct {
	value *AuthorshipCreateData
	isSet bool
}

func (v NullableAuthorshipCreateData) Get() *AuthorshipCreateData {
	return v.value
}

func (v *NullableAuthorshipCreateData) Set(val *AuthorshipCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorshipCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorshipCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorshipCreateData(val *AuthorshipCreateData) *NullableAuthorshipCreateData {
	return &NullableAuthorshipCreateData{value: val, isSet: true}
}

func (v NullableAuthorshipCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorshipCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


