/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagUpdateDataAttributes{}

// TagUpdateDataAttributes struct for TagUpdateDataAttributes
type TagUpdateDataAttributes struct {
	// tag status
	Status string `json:"status"`
	// tag type
	Type string `json:"type"`
	// tag description
	Description string `json:"description"`
	// tag color
	Color string `json:"color"`
	// tag icon
	Icon string `json:"icon"`
}

type _TagUpdateDataAttributes TagUpdateDataAttributes

// NewTagUpdateDataAttributes instantiates a new TagUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagUpdateDataAttributes(status string, type_ string, description string, color string, icon string) *TagUpdateDataAttributes {
	this := TagUpdateDataAttributes{}
	this.Status = status
	this.Type = type_
	this.Description = description
	this.Color = color
	this.Icon = icon
	return &this
}

// NewTagUpdateDataAttributesWithDefaults instantiates a new TagUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagUpdateDataAttributesWithDefaults() *TagUpdateDataAttributes {
	this := TagUpdateDataAttributes{}
	return &this
}

// GetStatus returns the Status field value
func (o *TagUpdateDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TagUpdateDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TagUpdateDataAttributes) SetStatus(v string) {
	o.Status = v
}

// GetType returns the Type field value
func (o *TagUpdateDataAttributes) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TagUpdateDataAttributes) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TagUpdateDataAttributes) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value
func (o *TagUpdateDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TagUpdateDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TagUpdateDataAttributes) SetDescription(v string) {
	o.Description = v
}

// GetColor returns the Color field value
func (o *TagUpdateDataAttributes) GetColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Color
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
func (o *TagUpdateDataAttributes) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color, true
}

// SetColor sets field value
func (o *TagUpdateDataAttributes) SetColor(v string) {
	o.Color = v
}

// GetIcon returns the Icon field value
func (o *TagUpdateDataAttributes) GetIcon() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *TagUpdateDataAttributes) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *TagUpdateDataAttributes) SetIcon(v string) {
	o.Icon = v
}

func (o TagUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type
	toSerialize["description"] = o.Description
	toSerialize["color"] = o.Color
	toSerialize["icon"] = o.Icon
	return toSerialize, nil
}

func (o *TagUpdateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"type",
		"description",
		"color",
		"icon",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagUpdateDataAttributes := _TagUpdateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagUpdateDataAttributes)

	if err != nil {
		return err
	}

	*o = TagUpdateDataAttributes(varTagUpdateDataAttributes)

	return err
}

type NullableTagUpdateDataAttributes struct {
	value *TagUpdateDataAttributes
	isSet bool
}

func (v NullableTagUpdateDataAttributes) Get() *TagUpdateDataAttributes {
	return v.value
}

func (v *NullableTagUpdateDataAttributes) Set(val *TagUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableTagUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableTagUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagUpdateDataAttributes(val *TagUpdateDataAttributes) *NullableTagUpdateDataAttributes {
	return &NullableTagUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableTagUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


