/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContentUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentUpdateData{}

// ContentUpdateData struct for ContentUpdateData
type ContentUpdateData struct {
	Type string `json:"type"`
	Attributes ContentUpdateDataAttributes `json:"attributes"`
}

type _ContentUpdateData ContentUpdateData

// NewContentUpdateData instantiates a new ContentUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentUpdateData(type_ string, attributes ContentUpdateDataAttributes) *ContentUpdateData {
	this := ContentUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewContentUpdateDataWithDefaults instantiates a new ContentUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentUpdateDataWithDefaults() *ContentUpdateData {
	this := ContentUpdateData{}
	return &this
}

// GetType returns the Type field value
func (o *ContentUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ContentUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ContentUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ContentUpdateData) GetAttributes() ContentUpdateDataAttributes {
	if o == nil {
		var ret ContentUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ContentUpdateData) GetAttributesOk() (*ContentUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ContentUpdateData) SetAttributes(v ContentUpdateDataAttributes) {
	o.Attributes = v
}

func (o ContentUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ContentUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentUpdateData := _ContentUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContentUpdateData)

	if err != nil {
		return err
	}

	*o = ContentUpdateData(varContentUpdateData)

	return err
}

type NullableContentUpdateData struct {
	value *ContentUpdateData
	isSet bool
}

func (v NullableContentUpdateData) Get() *ContentUpdateData {
	return v.value
}

func (v *NullableContentUpdateData) Set(val *ContentUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableContentUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableContentUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentUpdateData(val *ContentUpdateData) *NullableContentUpdateData {
	return &NullableContentUpdateData{value: val, isSet: true}
}

func (v NullableContentUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


