/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetHashtagDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetHashtagDataAttributes{}

// SetHashtagDataAttributes struct for SetHashtagDataAttributes
type SetHashtagDataAttributes struct {
	Tags []string `json:"tags"`
}

type _SetHashtagDataAttributes SetHashtagDataAttributes

// NewSetHashtagDataAttributes instantiates a new SetHashtagDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetHashtagDataAttributes(tags []string) *SetHashtagDataAttributes {
	this := SetHashtagDataAttributes{}
	this.Tags = tags
	return &this
}

// NewSetHashtagDataAttributesWithDefaults instantiates a new SetHashtagDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetHashtagDataAttributesWithDefaults() *SetHashtagDataAttributes {
	this := SetHashtagDataAttributes{}
	return &this
}

// GetTags returns the Tags field value
func (o *SetHashtagDataAttributes) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *SetHashtagDataAttributes) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *SetHashtagDataAttributes) SetTags(v []string) {
	o.Tags = v
}

func (o SetHashtagDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetHashtagDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tags"] = o.Tags
	return toSerialize, nil
}

func (o *SetHashtagDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetHashtagDataAttributes := _SetHashtagDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetHashtagDataAttributes)

	if err != nil {
		return err
	}

	*o = SetHashtagDataAttributes(varSetHashtagDataAttributes)

	return err
}

type NullableSetHashtagDataAttributes struct {
	value *SetHashtagDataAttributes
	isSet bool
}

func (v NullableSetHashtagDataAttributes) Get() *SetHashtagDataAttributes {
	return v.value
}

func (v *NullableSetHashtagDataAttributes) Set(val *SetHashtagDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSetHashtagDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSetHashtagDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetHashtagDataAttributes(val *SetHashtagDataAttributes) *NullableSetHashtagDataAttributes {
	return &NullableSetHashtagDataAttributes{value: val, isSet: true}
}

func (v NullableSetHashtagDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetHashtagDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


