/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateArticleContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateArticleContent{}

// UpdateArticleContent struct for UpdateArticleContent
type UpdateArticleContent struct {
	Data UpdateArticleContentData `json:"data"`
}

type _UpdateArticleContent UpdateArticleContent

// NewUpdateArticleContent instantiates a new UpdateArticleContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateArticleContent(data UpdateArticleContentData) *UpdateArticleContent {
	this := UpdateArticleContent{}
	this.Data = data
	return &this
}

// NewUpdateArticleContentWithDefaults instantiates a new UpdateArticleContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateArticleContentWithDefaults() *UpdateArticleContent {
	this := UpdateArticleContent{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateArticleContent) GetData() UpdateArticleContentData {
	if o == nil {
		var ret UpdateArticleContentData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateArticleContent) GetDataOk() (*UpdateArticleContentData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateArticleContent) SetData(v UpdateArticleContentData) {
	o.Data = v
}

func (o UpdateArticleContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateArticleContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateArticleContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateArticleContent := _UpdateArticleContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateArticleContent)

	if err != nil {
		return err
	}

	*o = UpdateArticleContent(varUpdateArticleContent)

	return err
}

type NullableUpdateArticleContent struct {
	value *UpdateArticleContent
	isSet bool
}

func (v NullableUpdateArticleContent) Get() *UpdateArticleContent {
	return v.value
}

func (v *NullableUpdateArticleContent) Set(val *UpdateArticleContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateArticleContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateArticleContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateArticleContent(val *UpdateArticleContent) *NullableUpdateArticleContent {
	return &NullableUpdateArticleContent{value: val, isSet: true}
}

func (v NullableUpdateArticleContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateArticleContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


