/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateContentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateContentResponse{}

// UpdateContentResponse struct for UpdateContentResponse
type UpdateContentResponse struct {
	Data UpdateContentResponseData `json:"data"`
}

type _UpdateContentResponse UpdateContentResponse

// NewUpdateContentResponse instantiates a new UpdateContentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateContentResponse(data UpdateContentResponseData) *UpdateContentResponse {
	this := UpdateContentResponse{}
	this.Data = data
	return &this
}

// NewUpdateContentResponseWithDefaults instantiates a new UpdateContentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateContentResponseWithDefaults() *UpdateContentResponse {
	this := UpdateContentResponse{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateContentResponse) GetData() UpdateContentResponseData {
	if o == nil {
		var ret UpdateContentResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateContentResponse) GetDataOk() (*UpdateContentResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateContentResponse) SetData(v UpdateContentResponseData) {
	o.Data = v
}

func (o UpdateContentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateContentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateContentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateContentResponse := _UpdateContentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateContentResponse)

	if err != nil {
		return err
	}

	*o = UpdateContentResponse(varUpdateContentResponse)

	return err
}

type NullableUpdateContentResponse struct {
	value *UpdateContentResponse
	isSet bool
}

func (v NullableUpdateContentResponse) Get() *UpdateContentResponse {
	return v.value
}

func (v *NullableUpdateContentResponse) Set(val *UpdateContentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateContentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateContentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateContentResponse(val *UpdateContentResponse) *NullableUpdateContentResponse {
	return &NullableUpdateContentResponse{value: val, isSet: true}
}

func (v NullableUpdateContentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateContentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


