/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateContentData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateContentData{}

// UpdateContentData struct for UpdateContentData
type UpdateContentData struct {
	Type string `json:"type"`
	Attributes UpdateContentDataAttributes `json:"attributes"`
}

type _UpdateContentData UpdateContentData

// NewUpdateContentData instantiates a new UpdateContentData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateContentData(type_ string, attributes UpdateContentDataAttributes) *UpdateContentData {
	this := UpdateContentData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateContentDataWithDefaults instantiates a new UpdateContentData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateContentDataWithDefaults() *UpdateContentData {
	this := UpdateContentData{}
	return &this
}

// GetType returns the Type field value
func (o *UpdateContentData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateContentData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateContentData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateContentData) GetAttributes() UpdateContentDataAttributes {
	if o == nil {
		var ret UpdateContentDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateContentData) GetAttributesOk() (*UpdateContentDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateContentData) SetAttributes(v UpdateContentDataAttributes) {
	o.Attributes = v
}

func (o UpdateContentData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateContentData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateContentData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateContentData := _UpdateContentData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateContentData)

	if err != nil {
		return err
	}

	*o = UpdateContentData(varUpdateContentData)

	return err
}

type NullableUpdateContentData struct {
	value *UpdateContentData
	isSet bool
}

func (v NullableUpdateContentData) Get() *UpdateContentData {
	return v.value
}

func (v *NullableUpdateContentData) Set(val *UpdateContentData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateContentData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateContentData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateContentData(val *UpdateContentData) *NullableUpdateContentData {
	return &NullableUpdateContentData{value: val, isSet: true}
}

func (v NullableUpdateContentData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateContentData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


