/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagUpdateData{}

// TagUpdateData struct for TagUpdateData
type TagUpdateData struct {
	// tag name
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes TagUpdateDataAttributes `json:"attributes"`
}

type _TagUpdateData TagUpdateData

// NewTagUpdateData instantiates a new TagUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagUpdateData(id string, type_ string, attributes TagUpdateDataAttributes) *TagUpdateData {
	this := TagUpdateData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewTagUpdateDataWithDefaults instantiates a new TagUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagUpdateDataWithDefaults() *TagUpdateData {
	this := TagUpdateData{}
	return &this
}

// GetId returns the Id field value
func (o *TagUpdateData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TagUpdateData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TagUpdateData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *TagUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TagUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TagUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *TagUpdateData) GetAttributes() TagUpdateDataAttributes {
	if o == nil {
		var ret TagUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *TagUpdateData) GetAttributesOk() (*TagUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *TagUpdateData) SetAttributes(v TagUpdateDataAttributes) {
	o.Attributes = v
}

func (o TagUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *TagUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagUpdateData := _TagUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagUpdateData)

	if err != nil {
		return err
	}

	*o = TagUpdateData(varTagUpdateData)

	return err
}

type NullableTagUpdateData struct {
	value *TagUpdateData
	isSet bool
}

func (v NullableTagUpdateData) Get() *TagUpdateData {
	return v.value
}

func (v *NullableTagUpdateData) Set(val *TagUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableTagUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableTagUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagUpdateData(val *TagUpdateData) *NullableTagUpdateData {
	return &NullableTagUpdateData{value: val, isSet: true}
}

func (v NullableTagUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


