/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTag{}

// UpdateTag struct for UpdateTag
type UpdateTag struct {
	Data UpdateTagData `json:"data"`
}

type _UpdateTag UpdateTag

// NewUpdateTag instantiates a new UpdateTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTag(data UpdateTagData) *UpdateTag {
	this := UpdateTag{}
	this.Data = data
	return &this
}

// NewUpdateTagWithDefaults instantiates a new UpdateTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTagWithDefaults() *UpdateTag {
	this := UpdateTag{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateTag) GetData() UpdateTagData {
	if o == nil {
		var ret UpdateTagData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateTag) GetDataOk() (*UpdateTagData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateTag) SetData(v UpdateTagData) {
	o.Data = v
}

func (o UpdateTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateTag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTag := _UpdateTag{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTag)

	if err != nil {
		return err
	}

	*o = UpdateTag(varUpdateTag)

	return err
}

type NullableUpdateTag struct {
	value *UpdateTag
	isSet bool
}

func (v NullableUpdateTag) Get() *UpdateTag {
	return v.value
}

func (v *NullableUpdateTag) Set(val *UpdateTag) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTag) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTag(val *UpdateTag) *NullableUpdateTag {
	return &NullableUpdateTag{value: val, isSet: true}
}

func (v NullableUpdateTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


