/*
REST API

REST API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleShortCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleShortCollection{}

// ArticleShortCollection struct for ArticleShortCollection
type ArticleShortCollection struct {
	Data ArticleShortCollectionData `json:"data"`
}

type _ArticleShortCollection ArticleShortCollection

// NewArticleShortCollection instantiates a new ArticleShortCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleShortCollection(data ArticleShortCollectionData) *ArticleShortCollection {
	this := ArticleShortCollection{}
	this.Data = data
	return &this
}

// NewArticleShortCollectionWithDefaults instantiates a new ArticleShortCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleShortCollectionWithDefaults() *ArticleShortCollection {
	this := ArticleShortCollection{}
	return &this
}

// GetData returns the Data field value
func (o *ArticleShortCollection) GetData() ArticleShortCollectionData {
	if o == nil {
		var ret ArticleShortCollectionData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ArticleShortCollection) GetDataOk() (*ArticleShortCollectionData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ArticleShortCollection) SetData(v ArticleShortCollectionData) {
	o.Data = v
}

func (o ArticleShortCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleShortCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ArticleShortCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleShortCollection := _ArticleShortCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleShortCollection)

	if err != nil {
		return err
	}

	*o = ArticleShortCollection(varArticleShortCollection)

	return err
}

type NullableArticleShortCollection struct {
	value *ArticleShortCollection
	isSet bool
}

func (v NullableArticleShortCollection) Get() *ArticleShortCollection {
	return v.value
}

func (v *NullableArticleShortCollection) Set(val *ArticleShortCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleShortCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleShortCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleShortCollection(val *ArticleShortCollection) *NullableArticleShortCollection {
	return &NullableArticleShortCollection{value: val, isSet: true}
}

func (v NullableArticleShortCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleShortCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


