openapi: 3.0.0
info:
  description: REST API
  title: REST API
  version: 0.0.1
servers:
- url: /
paths:
  /test:
    post:
      description: Test
      responses:
        "201":
          description: successfully
      tags:
      - Test
components:
  schemas:
    Article:
      properties:
        data:
          $ref: '#/components/schemas/ArticleData'
      required:
      - data
      - included
      type: object
    ArticleData:
      properties:
        id:
          description: article ID
          format: uuid
          type: string
        type:
          enum:
          - article
          type: string
        attributes:
          $ref: '#/components/schemas/ArticleAttributes'
        relationships:
          $ref: '#/components/schemas/ArticleData_relationships'
      required:
      - attributes
      - id
      - type
      type: object
    ArticleAttributes:
      properties:
        title:
          description: Article title
          example: Article title
          type: string
        status:
          description: Article status
          example: Article status
          type: string
        icon:
          description: Article link
          example: Article link
          type: string
        desc:
          description: Article description
          example: Article description
          type: string
        content:
          items:
            $ref: '#/components/schemas/Content'
          type: array
        likes:
          description: Article likes
          example: 100
          format: int64
          type: integer
        reposts:
          description: Article reposts
          example: 50
          format: int64
          type: integer
        updated_at:
          description: Updated at
          example: 2020-01-01T00:00:00Z
          format: date-time
          type: string
        created_at:
          description: Created at
          example: 2020-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - content
      - created_at
      - desc
      - icon
      - likes
      - reposts
      - status
      - title
      type: object
    ArticleInclude:
      properties:
        authors:
          items:
            $ref: '#/components/schemas/AuthorData'
          type: array
        tags:
          items:
            $ref: '#/components/schemas/TagData'
          type: array
      required:
      - authors
      - tags
      type: object
    ArticleCreate:
      properties:
        data:
          $ref: '#/components/schemas/ArticleCreate_data'
      required:
      - data
      - included
      type: object
    ArticleUpdate:
      properties:
        data:
          $ref: '#/components/schemas/ArticleUpdate_data'
      required:
      - data
      - included
      type: object
    Author:
      properties:
        data:
          $ref: '#/components/schemas/AuthorData'
      required:
      - data
      type: object
    AuthorData:
      properties:
        id:
          description: Author ID
          format: uuid
          type: string
        type:
          enum:
          - author
          type: string
        attributes:
          $ref: '#/components/schemas/AuthorAttributes'
      required:
      - attributes
      - id
      - type
      type: object
    AuthorAttributes:
      properties:
        name:
          type: string
        status:
          type: string
        desc:
          type: string
        avatar:
          type: string
        email:
          type: string
        telegram:
          type: string
        twitter:
          type: string
        updated_at:
          format: date-time
          type: string
        created_at:
          format: date-time
          type: string
      required:
      - created_at
      - name
      type: object
    AuthorCreate:
      properties:
        data:
          $ref: '#/components/schemas/AuthorCreate_data'
      required:
      - data
      type: object
    AuthorUpdate:
      properties:
        data:
          $ref: '#/components/schemas/AuthorUpdate_data'
      required:
      - data
      type: object
    AuthorshipCreate:
      properties:
        data:
          $ref: '#/components/schemas/AuthorshipCreate_data'
      required:
      - data
      type: object
    Content:
      properties:
        id:
          type: string
        type:
          type: string
        text:
          items:
            $ref: '#/components/schemas/Content_text_inner'
          type: array
        media:
          $ref: '#/components/schemas/Content_media'
        audio:
          $ref: '#/components/schemas/Content_audio'
      required:
      - id
      - type
      type: object
    ContentUpdate:
      properties:
        data:
          $ref: '#/components/schemas/ContentUpdate_data'
      required:
      - data
      type: object
    ContentUpdateResponse:
      properties:
        data:
          $ref: '#/components/schemas/ContentUpdateResponse_data'
      required:
      - data
      type: object
    Tag:
      properties:
        data:
          $ref: '#/components/schemas/TagData'
      required:
      - data
      type: object
    TagData:
      properties:
        id:
          description: tag name
          type: string
        type:
          enum:
          - tag
          type: string
        attributes:
          $ref: '#/components/schemas/TagAttributes'
      required:
      - attributes
      - id
      - type
      type: object
    TagAttributes:
      properties:
        status:
          type: string
        type:
          type: string
        color:
          description: Tag color
          example: '#FF5733'
          type: string
        icon:
          description: Tag icon
          example: https://example.com/icon.png
          type: string
        created_at:
          format: date-time
          type: string
      required:
      - color
      - created_at
      - icon
      - status
      - type
      type: object
    TagCreate:
      properties:
        data:
          $ref: '#/components/schemas/TagCreate_data'
      required:
      - data
      type: object
    TagUpdate:
      properties:
        data:
          $ref: '#/components/schemas/TagUpdate_data'
      required:
      - data
      type: object
    HashtagCreate:
      properties:
        data:
          $ref: '#/components/schemas/HashtagCreate_data'
      required:
      - data
      type: object
    Relationships:
      properties:
        id:
          type: string
        type:
          type: string
      required:
      - id
      - type
      type: object
    LinksDirect:
      properties:
        links:
          $ref: '#/components/schemas/LinksDirect_links'
        data:
          $ref: '#/components/schemas/LinksDirect_data'
      required:
      - links
      type: object
    LinksPagination:
      properties:
        previous:
          description: Link to the previous page
          type: string
        self:
          description: Link to the current page
          type: string
        next:
          description: Link to the next page
          type: string
      required:
      - self
      type: object
    LinksSelf:
      properties:
        self:
          description: Link to resources
          type: string
        update:
          description: Link to update resources
          type: string
      required:
      - self
      type: object
    ArticleData_relationships:
      properties:
        authors:
          items:
            $ref: '#/components/schemas/Relationships'
          type: array
        tags:
          items:
            $ref: '#/components/schemas/Relationships'
          type: array
      required:
      - authors
      - tags
      type: object
    ArticleCreate_data_attributes:
      properties:
        title:
          description: Article title
          example: Article title
          type: string
      required:
      - title
      type: object
    ArticleCreate_data:
      properties:
        type:
          enum:
          - article_create
          type: string
        attributes:
          $ref: '#/components/schemas/ArticleCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    ArticleUpdate_data_attributes:
      properties:
        status:
          description: Article status
          example: Article status
          type: string
        title:
          description: Article title
          example: Article title
          type: string
        icon:
          description: Article link
          example: Article link
          type: string
        desc:
          description: Article description
          example: Article description
          type: string
        content:
          additionalProperties: true
          description: Article content
          type: object
        authors:
          description: Authors ID uuid
          items:
            type: string
          type: array
        tags:
          items:
            type: string
          type: array
      type: object
    ArticleUpdate_data:
      properties:
        type:
          enum:
          - article_updated
          type: string
        attributes:
          $ref: '#/components/schemas/ArticleUpdate_data_attributes'
      required:
      - attributes
      - type
      type: object
    AuthorCreate_data_attributes:
      properties:
        name:
          type: string
        desc:
          type: string
        avatar:
          type: string
        email:
          type: string
        telegram:
          type: string
        twitter:
          type: string
      required:
      - name
      type: object
    AuthorCreate_data:
      properties:
        type:
          enum:
          - author_create
          type: string
        attributes:
          $ref: '#/components/schemas/AuthorCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    AuthorUpdate_data_attributes:
      properties:
        name:
          type: string
        desc:
          type: string
        avatar:
          type: string
        email:
          type: string
        telegram:
          type: string
        twitter:
          type: string
      type: object
    AuthorUpdate_data:
      properties:
        type:
          enum:
          - author_update
          type: string
        attributes:
          $ref: '#/components/schemas/AuthorUpdate_data_attributes'
      required:
      - attributes
      - type
      type: object
    AuthorshipCreate_data_attributes:
      properties:
        authorID:
          items:
            description: The ID of the author.
            format: uuid
            type: string
          type: array
        articleID:
          description: The ID of the article.
          format: uuid
          type: string
      required:
      - articleID
      - authors
      type: object
    AuthorshipCreate_data:
      properties:
        type:
          enum:
          - authorship_set
          type: string
        attributes:
          $ref: '#/components/schemas/AuthorshipCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    Content_text_inner:
      properties:
        text:
          type: string
        marks:
          items:
            type: string
          type: array
        color:
          type: string
        link:
          type: string
      type: object
    Content_media:
      properties:
        url:
          type: string
        caption:
          type: string
        alt:
          type: string
        width:
          type: integer
        height:
          type: integer
        source:
          type: string
      required:
      - alt
      - caption
      - height
      - source
      - url
      - width
      type: object
    Content_audio:
      properties:
        url:
          type: string
        duration:
          type: integer
        caption:
          type: string
        icon:
          type: string
      required:
      - caption
      - duration
      - icon
      - url
      type: object
    ContentUpdate_data_attributes:
      properties:
        sectionID:
          description: The ID of the section to be updated.
          type: integer
        action:
          description: The action to be performed on the content.
          enum:
          - add
          - remove
          - update
          type: string
        content:
          $ref: '#/components/schemas/Content'
      required:
      - action
      - content
      - sectionID
      type: object
    ContentUpdate_data:
      properties:
        type:
          enum:
          - article_content_update
          type: string
        attributes:
          $ref: '#/components/schemas/ContentUpdate_data_attributes'
      required:
      - attributes
      - type
      type: object
    ContentUpdateResponse_data_attributes:
      properties:
        status:
          description: The status of the content update operation.
          enum:
          - success
          - error
          type: string
        message:
          description: A message providing additional information about the operation.
          type: string
        section_number:
          type: integer
        content:
          $ref: '#/components/schemas/Content'
      required:
      - message
      - section_number
      - status
      type: object
    ContentUpdateResponse_data:
      properties:
        type:
          enum:
          - article_content_update_response
          type: string
        attributes:
          $ref: '#/components/schemas/ContentUpdateResponse_data_attributes'
      required:
      - attributes
      - type
      type: object
    TagCreate_data_attributes:
      properties:
        name:
          description: tag name
          type: string
        status:
          description: tag status
          enum:
          - active
          - inactive
          type: string
        type:
          description: tag type
          enum:
          - tag
          type: string
        description:
          description: tag description
          type: string
        color:
          description: tag color
          type: string
        icon:
          description: tag icon
          type: string
      required:
      - color
      - description
      - icon
      - name
      - status
      - type
      type: object
    TagCreate_data:
      properties:
        type:
          enum:
          - tag_create
          type: string
        attributes:
          $ref: '#/components/schemas/TagCreate_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    TagUpdate_data_attributes:
      properties:
        status:
          description: tag status
          enum:
          - active
          - inactive
          type: string
        type:
          description: tag type
          enum:
          - tag
          type: string
        description:
          description: tag description
          type: string
        color:
          description: tag color
          type: string
        icon:
          description: tag icon
          type: string
      required:
      - color
      - description
      - icon
      - status
      - type
      type: object
    TagUpdate_data:
      properties:
        id:
          description: tag name
          type: string
        type:
          enum:
          - tag_update
          type: string
        attributes:
          $ref: '#/components/schemas/TagUpdate_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    HashtagCreate_data_attributes:
      properties:
        tags:
          items:
            description: The ID of the author.
            format: uuid
            type: string
          type: array
        articleID:
          description: The ID of the article.
          format: uuid
          type: string
      required:
      - articleID
      - tags
      type: object
    HashtagCreate_data:
      properties:
        type:
          enum:
          - hashtag_set
          type: string
        attributes:
          $ref: '#/components/schemas/HashtagCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    LinksDirect_links:
      properties:
        self:
          description: Link to participants
          type: string
        related:
          description: Link to participants
          type: string
      required:
      - data
      - related
      - self
      type: object
    LinksDirect_data:
      properties:
        id:
          description: resources id
          type: string
        type:
          description: resources type
          type: string
      required:
      - id
      - type
      type: object
