openapi: 3.0.0
info:
  title: REST API
  description: REST API
  version: 0.0.1
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    Article:
      type: object
      required:
        - data
        - included
      properties:
        data:
          $ref: '#/components/schemas/ArticleData'
    ArticleData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: article ID
        type:
          type: string
          enum:
            - article
        attributes:
          $ref: '#/components/schemas/ArticleAttributes'
        relationships:
          type: object
          required:
            - authors
            - tags
          properties:
            authors:
              type: array
              items:
                $ref: '#/components/schemas/Relationships'
            tags:
              type: array
              items:
                $ref: '#/components/schemas/Relationships'
    ArticleAttributes:
      type: object
      required:
        - title
        - status
        - icon
        - desc
        - content
        - likes
        - reposts
        - created_at
      properties:
        title:
          type: string
          description: Article title
          example: Article title
        status:
          type: string
          description: Article status
          example: Article status
        icon:
          type: string
          description: Article link
          example: Article link
        desc:
          type: string
          description: Article description
          example: Article description
        content:
          type: array
          items:
            $ref: '#/components/schemas/Content'
        likes:
          type: integer
          description: Article likes
          format: int64
          example: 100
        reposts:
          type: integer
          description: Article reposts
          format: int64
          example: 50
        updated_at:
          type: string
          format: date-time
          description: Updated at
          example: '2020-01-01T00:00:00Z'
        created_at:
          type: string
          format: date-time
          description: Created at
          example: '2020-01-01T00:00:00Z'
    ArticleInclude:
      type: object
      required:
        - authors
        - tags
      properties:
        authors:
          type: array
          items:
            $ref: '#/components/schemas/AuthorData'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/TagData'
    ArticleCreate:
      type: object
      required:
        - data
        - included
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - article_create
            attributes:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  description: Article title
                  example: Article title
    ArticleUpdate:
      type: object
      required:
        - data
        - included
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - article_updated
            attributes:
              type: object
              properties:
                status:
                  type: string
                  description: Article status
                  example: Article status
                title:
                  type: string
                  description: Article title
                  example: Article title
                icon:
                  type: string
                  description: Article link
                  example: Article link
                desc:
                  type: string
                  description: Article description
                  example: Article description
                content:
                  type: object
                  additionalProperties: true
                  description: Article content
                authors:
                  type: array
                  items:
                    type: string
                  description: Authors ID uuid
                tags:
                  type: array
                  items:
                    type: string
    Author:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/AuthorData'
    AuthorData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: Author ID
        type:
          type: string
          enum:
            - author
        attributes:
          $ref: '#/components/schemas/AuthorAttributes'
    AuthorAttributes:
      type: object
      required:
        - name
        - created_at
      properties:
        name:
          type: string
        status:
          type: string
        desc:
          type: string
        avatar:
          type: string
        email:
          type: string
        telegram:
          type: string
        twitter:
          type: string
        updated_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
    AuthorCreate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - author_create
            attributes:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                desc:
                  type: string
                avatar:
                  type: string
                email:
                  type: string
                telegram:
                  type: string
                twitter:
                  type: string
    AuthorUpdate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - author_update
            attributes:
              type: object
              properties:
                name:
                  type: string
                desc:
                  type: string
                avatar:
                  type: string
                email:
                  type: string
                telegram:
                  type: string
                twitter:
                  type: string
    AuthorshipCreate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - authorship_set
            attributes:
              type: object
              required:
                - authors
                - articleID
              properties:
                authorID:
                  type: array
                  items:
                    type: string
                    format: uuid
                    description: The ID of the author.
                articleID:
                  type: string
                  format: uuid
                  description: The ID of the article.
    Content:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
        type:
          type: string
        text:
          type: array
          items:
            type: object
            properties:
              text:
                type: string
              marks:
                type: array
                items:
                  type: string
              color:
                type: string
              link:
                type: string
        media:
          type: object
          required:
            - url
            - caption
            - alt
            - width
            - height
            - source
          properties:
            url:
              type: string
            caption:
              type: string
            alt:
              type: string
            width:
              type: integer
            height:
              type: integer
            source:
              type: string
    Tag:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/TagData'
    TagData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          description: tag name
        type:
          type: string
          enum:
            - tag
        attributes:
          $ref: '#/components/schemas/TagAttributes'
    TagAttributes:
      type: object
      required:
        - status
        - type
        - color
        - icon
        - created_at
      properties:
        status:
          type: string
        type:
          type: string
        color:
          type: string
          description: Tag color
          example: '#FF5733'
        icon:
          type: string
          description: Tag icon
          example: 'https://example.com/icon.png'
        created_at:
          type: string
          format: date-time
    TagCreate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - tag_create
            attributes:
              type: object
              required:
                - name
                - status
                - type
                - description
                - color
                - icon
              properties:
                name:
                  type: string
                  description: tag name
                status:
                  type: string
                  enum:
                    - active
                    - inactive
                  description: tag status
                type:
                  type: string
                  enum:
                    - tag
                  description: tag type
                description:
                  type: string
                  description: tag description
                color:
                  type: string
                  description: tag color
                icon:
                  type: string
                  description: tag icon
    TagUpdate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              description: tag name
            type:
              type: string
              enum:
                - tag_update
            attributes:
              type: object
              required:
                - status
                - type
                - description
                - color
                - icon
              properties:
                status:
                  type: string
                  enum:
                    - active
                    - inactive
                  description: tag status
                type:
                  type: string
                  enum:
                    - tag
                  description: tag type
                description:
                  type: string
                  description: tag description
                color:
                  type: string
                  description: tag color
                icon:
                  type: string
                  description: tag icon
    HashtagCreate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - hashtag_set
            attributes:
              type: object
              required:
                - tags
                - articleID
              properties:
                tags:
                  type: array
                  items:
                    type: string
                    format: uuid
                    description: The ID of the author.
                articleID:
                  type: string
                  format: uuid.UUID
                  description: The ID of the article.
    Relationships:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
        type:
          type: string
    LinksDirect:
      type: object
      required:
        - links
      properties:
        links:
          type: object
          required:
            - self
            - related
            - data
          properties:
            self:
              type: string
              description: Link to participants
            related:
              type: string
              description: Link to participants
        data:
          type: object
          required:
            - id
            - type
          properties:
            id:
              type: string
              description: resources id
            type:
              type: string
              description: resources type
    LinksPagination:
      type: object
      required:
        - self
      properties:
        previous:
          type: string
          description: Link to the previous page
        self:
          type: string
          description: Link to the current page
        next:
          type: string
          description: Link to the next page
    LinksSelf:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          description: Link to resources
        update:
          type: string
          description: Link to update resources
