openapi: 3.0.0
info:
  title: REST API
  description:  REST API
  version: 0.0.1

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    Article:
      $ref: './spec/components/schemas/Article.yaml'
    ArticleData:
      $ref: './spec/components/schemas/ArticleData.yaml'
    ArticleAttributes:
      $ref: './spec/components/schemas/ArticleAttributes.yaml'
    ArticleInclude:
      $ref: './spec/components/schemas/ArticleInclude.yaml'
    CreateArticle:
      $ref: './spec/components/schemas/CreateArticle.yaml'
    UpdateArticle:
      $ref: './spec/components/schemas/UpdateArticle.yaml'
    ArticleShort:
      $ref: './spec/components/schemas/ArticleShort.yaml'
    ArticleShortCollection:
      $ref: './spec/components/schemas/ArticleShortCollection.yaml'
    ArticleWithRecommends:
      $ref: './spec/components/schemas/ArticleWithRecommends.yaml'
    ArticleWithRecommendsInclude:
      $ref: './spec/components/schemas/ArticleWithRecommendsInclude.yaml'

    Author:
      $ref: './spec/components/schemas/Author.yaml'
    AuthorData:
      $ref: './spec/components/schemas/AuthorData.yaml'
    AuthorAttributes:
      $ref: './spec/components/schemas/AuthorAttributes.yaml'
    CreateAuthor:
      $ref: './spec/components/schemas/CreateAuthor.yaml'
    UpdateAuthor:
      $ref: './spec/components/schemas/UpdateAuthor.yaml'
    AuthorsCollection:
      $ref: './spec/components/schemas/AuthorsCollection.yaml'

    SetAuthorship:
      $ref: './spec/components/schemas/SetAuthorship.yaml'

    Content:
      $ref: './spec/components/schemas/Content.yaml'
    UpdateContent:
      $ref: './spec/components/schemas/UpdateContent.yaml'
    UpdateContentResponse:
      $ref: './spec/components/schemas/UpdateContentResponse.yaml'

    Tag:
      $ref: './spec/components/schemas/Tag.yaml'
    TagData:
      $ref: './spec/components/schemas/TagData.yaml'
    TagAttributes:
      $ref: './spec/components/schemas/TagAttributes.yaml'
    CreateTag:
      $ref: './spec/components/schemas/CreateTag.yaml'
    UpdateTag:
      $ref: './spec/components/schemas/UpdateTag.yaml'
    TagCollection:
      $ref: './spec/components/schemas/TagCollection.yaml'

    SetHashtag:
      $ref: './spec/components/schemas/SetHashtag.yaml'

    Relationships:
      $ref: './spec/components/schemas/Relationships.yaml'

    LinksDirect:
      $ref: './spec/components/schemas/LinksDirect.yaml'
    LinksPagination:
      $ref: './spec/components/schemas/LinksPagination.yaml'
    LinksSelf:
      $ref: './spec/components/schemas/LinksSelf.yaml'
